# Generated by Django 6.0.4 on 2026-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_lot_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='classification_source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fonte'),
        ),
    ]
