# Generated by Django 5.2.15 on 2026-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_pendingentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
