# Generated by Django 5.2.15 on 2026-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_rejectedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='snapshot_catalog_version',
            field=models.IntegerField(default=0, verbose_name='Versão do snapshot'),
        ),
    ]
