# Generated by Django 5.2.15 on 2026-07-06 23:42

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_inventoryentry_snapshot_catalog_version'),
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'base_manager_name': 'all_companies', 'ordering': ['-last_updated'], 'verbose_name': 'Entrada de Estoque', 'verbose_name_plural': 'Entradas de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'base_manager_name': 'all_companies', 'ordering': ['-number'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='pendingentry',
            options={'base_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Pendente de Conferência', 'verbose_name_plural': 'Pendentes de Conferência'},
        ),
        migrations.AlterModelOptions(
            name='rejectedentry',
            options={'base_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Reprovado', 'verbose_name_plural': 'Reprovados'},
        ),
        migrations.AlterModelManagers(
            name='inventoryentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lot',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pendingentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rejectedentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lot',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='tenancy.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='lot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pendingentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='rejectedentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='operator',
            field=models.ForeignKey(help_text='Quem abriu o lote (o lote pertence à EMPRESA, não a ele).', on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
    ]
