# Generated by Django 5.2.15 on 2026-07-17 01:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_t4_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-last_updated'], 'verbose_name': 'Entrada de Estoque', 'verbose_name_plural': 'Entradas de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-number'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='pendingentry',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Pendente de Conferência', 'verbose_name_plural': 'Pendentes de Conferência'},
        ),
        migrations.AlterModelOptions(
            name='rejectedentry',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Reprovado', 'verbose_name_plural': 'Reprovados'},
        ),
        migrations.AlterModelManagers(
            name='inventoryentry',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lot',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pendingentry',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rejectedentry',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='price_gen',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Chave de preço: geração'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='price_key_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sem chave (motivo)'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='price_kind',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Chave de preço: tipo'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='price_tier_unit',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Chave de preço: unidade'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='price_tier_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Chave de preço: faixa'),
        ),
    ]
