# Generated by Django 5.2.15 on 2026-08-01 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_alter_inventoryentry_options_alter_lot_options_and_more'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Backfill 2026-08-01: lotes pré-existentes = 'phone' (estoque legado
        # misturado = grau-celular, acordado com o comprador). preserve_default
        # =False: lote NOVO não tem default — a abertura exige a escolha.
        migrations.AddField(
            model_name='lot',
            name='origin',
            field=models.CharField(choices=[('phone', 'Celular'), ('pcb', 'PCB')], default='phone', help_text='Classe de placa de onde os chips saíram (celular × PCB) — define a tabela de preço do eMMC.', max_length=5, verbose_name='Origem'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['phone', 'pcb'])), name='lot_origin_vocab'),
        ),
    ]
