# Generated by Django 5.2.15 on 2026-08-01 13:32

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_lot_origin_lot_lot_origin_vocab'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('origin', models.CharField(choices=[('phone', 'Celular'), ('pcb', 'PCB')], help_text='Classe de placa de onde os chips saíram (celular × PCB) — define a tabela de preço do eMMC.', max_length=5, verbose_name='Origem')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10, verbose_name='Status')),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Câmbio travado (1¥→US$)')),
                ('fx_source', models.CharField(blank=True, default='', max_length=80, verbose_name='Fonte do câmbio')),
                ('fx_locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Câmbio travado em')),
                ('fx_is_fallback', models.BooleanField(default=False, verbose_name='Câmbio de fallback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='fx_is_fallback',
            field=models.BooleanField(default=False, verbose_name='Câmbio de fallback'),
        ),
        migrations.AddField(
            model_name='lot',
            name='fx_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Câmbio travado em'),
        ),
        migrations.AddField(
            model_name='lot',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Câmbio travado (1¥→US$)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='fx_source',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Fonte do câmbio'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lot',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;', hash='efc7d4b286ed12944e0d3dc72760dcaa1c625164', operation='INSERT', pgid='pgtrigger_insert_insert_d35a3', table='estoque_lot', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lot',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;', hash='c4fb3e630a38db97b9e347bf745b845fe867b801', operation='UPDATE', pgid='pgtrigger_update_update_927aa', table='estoque_lot', when='AFTER')),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='company',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='operator',
            field=models.ForeignKey(db_constraint=False, help_text='Quem abriu o lote (o lote pertence à EMPRESA, não a ele).', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='estoque.lot'),
        ),
    ]
