# Generated by Django 5.2.15 on 2026-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0017_lotevent_lot_fx_is_fallback_lot_fx_locked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Token de envio"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de envio (idempotência)",
                "verbose_name_plural": "Tokens de envio (idempotência)",
            },
        ),
    ]
