"""Lot.closed_by — quem fechou o lote (2026-08-18).

ADITIVA e nullable: nenhum backfill (RunPython em tabela com RLS exigiria o
GUC de plataforma no migrate do Render — armadilha conhecida). Lote fechado
antes disto lê o ``LotPricing.closed_by`` pelo ``Lot.closed_by_user``.

O ciclo remove/recria trigger é do pghistory: coluna nova no modelo rastreado
muda o INSERT do gatilho de evento. Padrão idêntico ao da 0017 (câmbio).
"""

# Generated by Django 5.2.15

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0018_submittoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="lot",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="lot",
            name="update_update",
        ),
        migrations.AddField(
            model_name="lot",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Quem fechou o lote (registro do documento comercial). Vazio em lotes fechados antes de 2026-08-18.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fechado por",
            ),
        ),
        migrations.AddField(
            model_name="lotevent",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Quem fechou o lote (registro do documento comercial). Vazio em lotes fechados antes de 2026-08-18.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fechado por",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lot",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="7dea034bdfb8d53209655f42d8df06f15c016da7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_d35a3",
                    table="estoque_lot",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lot",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="876c00066ee461db55f82e3e1c49ee8feb2e24cc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_927aa",
                    table="estoque_lot",
                    when="AFTER",
                ),
            ),
        ),
    ]
