"""Lot.code_str — o código do lote CONGELADO na criação.

ADITIVA, tudo blank/default='' — **sem backfill de propósito**: documento
existente fica sem `code_str` e a propriedade `code` devolve o formato ANTIGO,
que é o que está no papel já impresso (decisão do dono, 2026-08-18: formato
novo só em documento NOVO).

O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 16:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0019_lot_closed_by"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="lot",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="lot",
            name="update_update",
        ),
        migrations.AddField(
            model_name="lot",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="lotevent",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lot",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "code_str", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."code_str", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="8f2a952d1b78cbcc29c9110634c2279cd1580cbb",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_d35a3",
                    table="estoque_lot",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lot",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "code_str", "company_id", "created_at", "description", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."code_str", NEW."company_id", NEW."created_at", NEW."description", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="904a4d3ac6cb1560c0854d50e76d7c79cffb37be",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_927aa",
                    table="estoque_lot",
                    when="AFTER",
                ),
            ),
        ),
    ]
