# Generated by Django 5.2.15 on 2026-09-01 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0021_lot_origin_ram"),
        ("tenancy", "0011_company_service_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lot",
            name="lot_origin_vocab",
        ),
        migrations.AlterField(
            model_name="lot",
            name="origin",
            field=models.CharField(
                choices=[
                    ("phone", "Celular"),
                    ("pcb", "PCB"),
                    ("ram", "Módulo de memória"),
                    ("mixed", "MIXED"),
                    ("k9", "K9"),
                ],
                help_text="Classe de placa de onde os chips saíram (celular × PCB) — define a tabela de preço do eMMC.",
                max_length=5,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="lotevent",
            name="origin",
            field=models.CharField(
                choices=[
                    ("phone", "Celular"),
                    ("pcb", "PCB"),
                    ("ram", "Módulo de memória"),
                    ("mixed", "MIXED"),
                    ("k9", "K9"),
                ],
                help_text="Classe de placa de onde os chips saíram (celular × PCB) — define a tabela de preço do eMMC.",
                max_length=5,
                verbose_name="Origem",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin__in", ["phone", "pcb", "ram", "mixed", "k9"])
                ),
                name="lot_origin_vocab",
            ),
        ),
    ]
