# Generated by Django 5.2.15 on 2026-09-02 15:23

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_origens_legadas_mixed_k9'),
        ('tenancy', '0013_alter_company_code_alter_companyevent_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lot',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lot',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='lot',
            name='unique_lot_company_number',
        ),
        migrations.AddField(
            model_name='lot',
            name='doc_year',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ano do documento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='ever_closed',
            field=models.BooleanField(default=False, editable=False, help_text='Marca que o lote chegou a ser fechado alguma vez — o número dele não volta mais para a sequência. Reabrir não desmarca.', verbose_name='Já foi fechado'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='doc_year',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ano do documento'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='ever_closed',
            field=models.BooleanField(default=False, editable=False, help_text='Marca que o lote chegou a ser fechado alguma vez — o número dele não volta mais para a sequência. Reabrir não desmarca.', verbose_name='Já foi fechado'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lot',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "code_str", "company_id", "created_at", "description", "doc_year", "ever_closed", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."code_str", NEW."company_id", NEW."created_at", NEW."description", NEW."doc_year", NEW."ever_closed", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;', hash='e40e91e38f725a8c1941293f587ee5415c1ffb29', operation='INSERT', pgid='pgtrigger_insert_insert_d35a3', table='estoque_lot', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lot',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "estoque_lotevent" ("branch_id", "closed_at", "closed_by_id", "code_str", "company_id", "created_at", "description", "doc_year", "ever_closed", "fx_is_fallback", "fx_locked_at", "fx_rate", "fx_source", "id", "number", "operator_id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."branch_id", NEW."closed_at", NEW."closed_by_id", NEW."code_str", NEW."company_id", NEW."created_at", NEW."description", NEW."doc_year", NEW."ever_closed", NEW."fx_is_fallback", NEW."fx_locked_at", NEW."fx_rate", NEW."fx_source", NEW."id", NEW."number", NEW."operator_id", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;', hash='4fbcf2ab15c194750dd4bb65abc848eeb34bab6e', operation='UPDATE', pgid='pgtrigger_update_update_927aa', table='estoque_lot', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('company', 'doc_year', 'number'), name='unique_lot_company_year_number'),
        ),
    ]
