"""A TORNEIRA origem × tipo (dono, 2026-09-02) — só o schema; a 0025 semeia.

Tabela GLOBAL: sem `company` e sem RLS, igual ao `ProfitabilityConfig`. A régua
é do NEGÓCIO (combinada com o comprador), não de cada empresa-cliente, e por
isso não há o que isolar. Declarada em `TenancyDeclarationTests`.

`origin` e `kind` nascem SEM `choices`: choices congela na migração e toda
origem/kind novo viraria um `AlterField` que não muda uma linha de banco. Quem
cobra linha para vocabulário novo é o `PoliticaOrigemDeclaracaoTests`.
"""
# Generated by Django 5.2.15 on 2026-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0023_remove_lot_insert_insert_remove_lot_update_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliticaOrigemTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(max_length=5, verbose_name="Origem do lote"),
                ),
                ("kind", models.CharField(max_length=8, verbose_name="Tipo de chip")),
                (
                    "permitido",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para FECHAR a torneira: este tipo para de ser aceito em lotes desta origem. O que já foi lançado não muda.",
                        verbose_name="Permitido",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Política de origem × tipo",
                "verbose_name_plural": "Política de origem × tipo",
                "ordering": ("origin", "kind"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origin", "kind"), name="politica_origem_tipo_unica"
                    )
                ],
            },
        ),
    ]
