# Generated by Django 5.2.15 on 2026-09-20 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_seed_politica_origem'),
        ('tenancy', '0013_alter_company_code_alter_companyevent_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='bus_width',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='bus_width_source',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Origem da largura'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='width_class',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Classe de largura'),
        ),
        migrations.AddField(
            model_name='pendingentry',
            name='bus_width',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='pendingentry',
            name='bus_width_source',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Origem da largura'),
        ),
        migrations.AddField(
            model_name='pendingentry',
            name='width_class',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Classe de largura'),
        ),
        migrations.AddField(
            model_name='rejectedentry',
            name='bus_width',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='rejectedentry',
            name='bus_width_source',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Origem da largura'),
        ),
        migrations.AddField(
            model_name='rejectedentry',
            name='width_class',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Classe de largura'),
        ),
        migrations.AddConstraint(
            model_name='inventoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width__in', ('', 'x4', 'x8', 'x16', 'x32', 'x64'))), name='inventoryentry_bus_width_vocab'),
        ),
        migrations.AddConstraint(
            model_name='inventoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('width_class__in', ('', 'narrow', 'wide'))), name='inventoryentry_width_class_vocab'),
        ),
        migrations.AddConstraint(
            model_name='inventoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width_source__in', ('', 'banco', 'familia', 'gramatica', 'revisao'))), name='inventoryentry_bw_source_vocab'),
        ),
        migrations.AddConstraint(
            model_name='pendingentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width__in', ('', 'x4', 'x8', 'x16', 'x32', 'x64'))), name='pendingentry_bus_width_vocab'),
        ),
        migrations.AddConstraint(
            model_name='pendingentry',
            constraint=models.CheckConstraint(condition=models.Q(('width_class__in', ('', 'narrow', 'wide'))), name='pendingentry_width_class_vocab'),
        ),
        migrations.AddConstraint(
            model_name='pendingentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width_source__in', ('', 'banco', 'familia', 'gramatica', 'revisao'))), name='pendingentry_bw_source_vocab'),
        ),
        migrations.AddConstraint(
            model_name='rejectedentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width__in', ('', 'x4', 'x8', 'x16', 'x32', 'x64'))), name='rejectedentry_bus_width_vocab'),
        ),
        migrations.AddConstraint(
            model_name='rejectedentry',
            constraint=models.CheckConstraint(condition=models.Q(('width_class__in', ('', 'narrow', 'wide'))), name='rejectedentry_width_class_vocab'),
        ),
        migrations.AddConstraint(
            model_name='rejectedentry',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width_source__in', ('', 'banco', 'familia', 'gramatica', 'revisao'))), name='rejectedentry_bw_source_vocab'),
        ),
    ]
