# Generated by Django 5.2.15 on 2026-07-07 13:24

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chips', '0022_searchlog_company_unknownchip_company'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staleness_days', models.PositiveIntegerField(default=90, help_text='Cotação mais antiga que isto é exibida como "≈ referência". Sem quote_date = sempre referência.', verbose_name='Cotação velha após (dias)')),
                ('default_scenario', models.CharField(choices=[('low', 'Baixo (início da faixa)'), ('mid', 'Médio (meio da faixa)'), ('high', 'Alto (fim da faixa)')], default='mid', help_text='Qual valor usar por padrão quando o preço é uma faixa.', max_length=4, verbose_name='Cenário padrão de faixa')),
            ],
            options={
                'verbose_name': 'Configuração de Preços',
                'verbose_name_plural': 'Configuração de Preços',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(blank=True, help_text='De quem é este comprador. VAZIO = comprador de plataforma (marketplace futuro) — invisível às empresas até lá.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='tenancy.company', verbose_name='Empresa')),
                ('users', models.ManyToManyField(blank=True, help_text='Usuários que acessam o dashboard /partner/ deste comprador.', related_name='buyers', to=settings.AUTH_USER_MODEL, verbose_name='Contas do comprador')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'ordering': ['name'],
                'base_manager_name': 'all_companies',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(db_index=False, max_length=60, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='De quem é este comprador. VAZIO = comprador de plataforma (marketplace futuro) — invisível às empresas até lá.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pricing.buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR'), ('gddr', 'GDDR')], max_length=8, verbose_name='Tipo')),
                ('gen', models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4X / DDR3L / GDDR6… Vazio para eMMC/UFS. Em eMCP/uMCP é a geração da RAM.', max_length=12, verbose_name='Geração')),
                ('tier_value', models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (a RAM fica FORA da chave — regra do comprador). DDR/GDDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade')),
                ('tier_unit', models.CharField(choices=[('GB', 'GB (pacote)'), ('Gb', 'Gb (die)')], max_length=2, verbose_name='Unidade')),
                ('status', models.CharField(choices=[('quoted', 'Cotado'), ('no_buy', 'Não compra'), ('unquoted', 'Aguardando cotação')], default='unquoted', max_length=10, verbose_name='Status')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD mín.')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD máx.')),
                ('quote_date', models.DateField(blank=True, help_text='Sem data = tratado como referência antiga (≈).', null=True, verbose_name='Data da cotação')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='Fonte')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Setado pelo chamador (admin/dashboard/import).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
                'ordering': ['price_list', 'kind', 'gen', 'tier_value'],
                'base_manager_name': 'all_companies',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('brand', models.ForeignKey(blank=True, help_text='VAZIO = lista GENÉRICA do comprador (marcas sem lista própria).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chips.brand', verbose_name='Marca')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='pricing.buyer', verbose_name='Comprador')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('inherits_from', models.ForeignKey(blank=True, help_text='Fallback como DADO (regra do comprador): linha ausente aqui é buscada na lista-alvo. 1 nível; mesmo comprador.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherited_by', to='pricing.pricelist', verbose_name='Herda de')),
            ],
            options={
                'verbose_name': 'Lista de preços',
                'verbose_name_plural': 'Listas de preços',
                'ordering': ['buyer__name', 'brand__name'],
                'base_manager_name': 'all_companies',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR'), ('gddr', 'GDDR')], max_length=8, verbose_name='Tipo')),
                ('gen', models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4X / DDR3L / GDDR6… Vazio para eMMC/UFS. Em eMCP/uMCP é a geração da RAM.', max_length=12, verbose_name='Geração')),
                ('tier_value', models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (a RAM fica FORA da chave — regra do comprador). DDR/GDDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade')),
                ('tier_unit', models.CharField(choices=[('GB', 'GB (pacote)'), ('Gb', 'Gb (die)')], max_length=2, verbose_name='Unidade')),
                ('status', models.CharField(choices=[('quoted', 'Cotado'), ('no_buy', 'Não compra'), ('unquoted', 'Aguardando cotação')], default='unquoted', max_length=10, verbose_name='Status')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD mín.')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD máx.')),
                ('quote_date', models.DateField(blank=True, help_text='Sem data = tratado como referência antiga (≈).', null=True, verbose_name='Data da cotação')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='Fonte')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pricing.price')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Setado pelo chamador (admin/dashboard/import).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('price_list', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.pricelist', verbose_name='Lista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='price',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.pricelist', verbose_name='Lista'),
        ),
        migrations.CreateModel(
            name='PriceListEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, help_text='VAZIO = lista GENÉRICA do comprador (marcas sem lista própria).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.brand', verbose_name='Marca')),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.buyer', verbose_name='Comprador')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('inherits_from', models.ForeignKey(blank=True, db_constraint=False, help_text='Fallback como DADO (regra do comprador): linha ausente aqui é buscada na lista-alvo. 1 nível; mesmo comprador.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.pricelist', verbose_name='Herda de')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pricing.pricelist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='buyer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_buyer_company_name'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='465ee154d874771e4899ba8a21bfb6c372e2ee73', operation='INSERT', pgid='pgtrigger_insert_insert_35de3', table='pricing_buyer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='3fbfff6be712be388ea3c80db8e38a7c93176eb9', operation='UPDATE', pgid='pgtrigger_update_update_2c806', table='pricing_buyer', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('buyer', 'brand'), name='unique_pricelist_buyer_brand'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('buyer',), name='unique_generic_list_per_buyer'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelist',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_pricelistevent" ("active", "brand_id", "buyer_id", "company_id", "created_at", "id", "inherits_from_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."brand_id", NEW."buyer_id", NEW."company_id", NEW."created_at", NEW."id", NEW."inherits_from_id", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='d0facdc4d715d48273b8fbf8b1f881fccbed348d', operation='INSERT', pgid='pgtrigger_insert_insert_d5093', table='pricing_pricelist', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelist',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_pricelistevent" ("active", "brand_id", "buyer_id", "company_id", "created_at", "id", "inherits_from_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."brand_id", NEW."buyer_id", NEW."company_id", NEW."created_at", NEW."id", NEW."inherits_from_id", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='780ddc870599adbb8d4a0384384322c1148b7517', operation='UPDATE', pgid='pgtrigger_update_update_6d494', table='pricing_pricelist', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['company', 'kind', 'gen'], name='price_company_kind_gen'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('price_list', 'kind', 'gen', 'tier_value', 'tier_unit'), name='unique_price_key'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['ddr', 'emcp', 'emmc', 'gddr', 'lpddr', 'ufs', 'umcp'])), name='price_kind_vocab'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['quoted', 'no_buy', 'unquoted'])), name='price_status_vocab'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('tier_unit__in', ['GB', 'Gb'])), name='price_tier_unit_vocab'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('tier_value__gt', 0)), name='price_tier_positive'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('price_min__isnull', True), ('price_max__isnull', True), ('price_min__lte', models.F('price_max')), _connector='OR'), name='price_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'quoted'), _negated=True), models.Q(('price_min__isnull', False), ('price_max__isnull', False)), _connector='OR'), name='price_quoted_has_value'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'quoted'), models.Q(('price_min__isnull', True), ('price_max__isnull', True)), _connector='OR'), name='price_unpriced_is_null'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='price',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_priceevent" ("company_id", "gen", "id", "kind", "last_updated", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id", "price_max", "price_min", "quote_date", "source", "status", "tier_unit", "tier_value", "updated_by_id") VALUES (NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."last_updated", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_list_id", NEW."price_max", NEW."price_min", NEW."quote_date", NEW."source", NEW."status", NEW."tier_unit", NEW."tier_value", NEW."updated_by_id"); RETURN NULL;', hash='369538fb3f405307311ebdc57b9b5be0e3c70df5', operation='INSERT', pgid='pgtrigger_insert_insert_12aba', table='pricing_price', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='price',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_priceevent" ("company_id", "gen", "id", "kind", "last_updated", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id", "price_max", "price_min", "quote_date", "source", "status", "tier_unit", "tier_value", "updated_by_id") VALUES (NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."last_updated", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_list_id", NEW."price_max", NEW."price_min", NEW."quote_date", NEW."source", NEW."status", NEW."tier_unit", NEW."tier_value", NEW."updated_by_id"); RETURN NULL;', hash='6f210b0de54bfb6d0e149df8041e8dd829a010c7', operation='UPDATE', pgid='pgtrigger_update_update_c5d0c', table='pricing_price', when='AFTER')),
        ),
    ]
