# Generated by Django 5.2.15 on 2026-07-07 14:29

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_t4_rls'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('pricing', '0002_rls'),
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (baixo)')),
                ('total_mid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (médio)')),
                ('total_high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (alto)')),
                ('priced_units', models.PositiveIntegerField(verbose_name='Unid. precificadas')),
                ('total_units', models.PositiveIntegerField(verbose_name='Unid. totais')),
                ('priced_lines', models.PositiveIntegerField(verbose_name='Linhas precificadas')),
                ('total_lines', models.PositiveIntegerField(verbose_name='Linhas totais')),
                ('lines', models.JSONField(default=list, verbose_name='Linhas (auditoria)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Congelado em')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.buyer', verbose_name='Comprador')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='estoque.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Valoração de lote (congelada)',
                'verbose_name_plural': 'Valorações de lote (congeladas)',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_companies',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LotPricingEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('total_low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (baixo)')),
                ('total_mid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (médio)')),
                ('total_high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (alto)')),
                ('priced_units', models.PositiveIntegerField(verbose_name='Unid. precificadas')),
                ('total_units', models.PositiveIntegerField(verbose_name='Unid. totais')),
                ('priced_lines', models.PositiveIntegerField(verbose_name='Linhas precificadas')),
                ('total_lines', models.PositiveIntegerField(verbose_name='Linhas totais')),
                ('lines', models.JSONField(default=list, verbose_name='Linhas (auditoria)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Congelado em')),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.buyer', verbose_name='Comprador')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('lot', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='estoque.lot', verbose_name='Lote')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pricing.lotpricing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='lotpricing',
            index=models.Index(fields=['company', 'lot'], name='lotpricing_company_lot'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lotpricing',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_lotpricingevent" ("buyer_id", "closed_by_id", "company_id", "created_at", "id", "lines", "lot_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priced_lines", "priced_units", "total_high", "total_lines", "total_low", "total_mid", "total_units") VALUES (NEW."buyer_id", NEW."closed_by_id", NEW."company_id", NEW."created_at", NEW."id", NEW."lines", NEW."lot_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priced_lines", NEW."priced_units", NEW."total_high", NEW."total_lines", NEW."total_low", NEW."total_mid", NEW."total_units"); RETURN NULL;', hash='e2e8e79e63414bea7815fb0b7790e597d69d265b', operation='INSERT', pgid='pgtrigger_insert_insert_0b4b7', table='pricing_lotpricing', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lotpricing',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_lotpricingevent" ("buyer_id", "closed_by_id", "company_id", "created_at", "id", "lines", "lot_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priced_lines", "priced_units", "total_high", "total_lines", "total_low", "total_mid", "total_units") VALUES (NEW."buyer_id", NEW."closed_by_id", NEW."company_id", NEW."created_at", NEW."id", NEW."lines", NEW."lot_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priced_lines", NEW."priced_units", NEW."total_high", NEW."total_lines", NEW."total_low", NEW."total_mid", NEW."total_units"); RETURN NULL;', hash='f208d7af01ef6dc35a271d1cd8671e5ff5c764d1', operation='UPDATE', pgid='pgtrigger_update_update_71f5f', table='pricing_lotpricing', when='AFTER')),
        ),
    ]
