# Generated by Django 5.2.15 on 2026-07-07 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_fixed_price'),
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='price_status_vocab',
        ),
        migrations.AlterField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('quoted', 'Cotado'), ('unquoted', 'Não cotado'), ('not_made', 'Não fabricado'), ('no_buy', 'Não compro')], default='unquoted', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='status',
            field=models.CharField(choices=[('quoted', 'Cotado'), ('unquoted', 'Não cotado'), ('not_made', 'Não fabricado'), ('no_buy', 'Não compro')], default='unquoted', max_length=10, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['quoted', 'no_buy', 'unquoted', 'not_made'])), name='price_status_vocab'),
        ),
    ]
