# Generated by Django 5.2.15 on 2026-07-07 18:35

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('pricing', '0006_remove_price_price_status_vocab_alter_price_status_and_more'),
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('quoted', 'Cotado'), ('unquoted', 'Não cotado'), ('not_made', 'Não fabricado'), ('no_buy', 'Não compro')], max_length=10, verbose_name='Novo estado')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Novo USD')),
                ('old_status', models.CharField(max_length=10, verbose_name='Estado anterior')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD anterior')),
                ('review_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Pedido em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='pricing.price', verbose_name='Linha')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pedido por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Mudança de preço (revisão)',
                'verbose_name_plural': 'Mudanças de preço (revisão)',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_companies',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceChangeRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('new_status', models.CharField(choices=[('quoted', 'Cotado'), ('unquoted', 'Não cotado'), ('not_made', 'Não fabricado'), ('no_buy', 'Não compro')], max_length=10, verbose_name='Novo estado')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Novo USD')),
                ('old_status', models.CharField(max_length=10, verbose_name='Estado anterior')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='USD anterior')),
                ('review_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Pedido em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pricing.pricechangerequest')),
                ('price', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.price', verbose_name='Linha')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pedido por')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='pricechangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('review_status', 'pending')), fields=('price',), name='one_pending_per_price'),
        ),
        migrations.AddConstraint(
            model_name='pricechangerequest',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='pcr_review_vocab'),
        ),
        migrations.AddConstraint(
            model_name='pricechangerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('new_status', 'quoted'), _negated=True), ('new_price__isnull', False), _connector='OR'), name='pcr_quoted_has_value'),
        ),
        migrations.AddConstraint(
            model_name='pricechangerequest',
            constraint=models.CheckConstraint(condition=models.Q(('new_status', 'quoted'), ('new_price__isnull', True), _connector='OR'), name='pcr_unpriced_is_null'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id"); RETURN NULL;', hash='a2d0e84899befa394c93816d442bee068940db5a', operation='INSERT', pgid='pgtrigger_insert_insert_4e6cd', table='pricing_pricechangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id"); RETURN NULL;', hash='2a166be72ab6a7cc1c4a40b1eb3f7a75bb44e7e9', operation='UPDATE', pgid='pgtrigger_update_update_3599f', table='pricing_pricechangerequest', when='AFTER')),
        ),
    ]
