# Generated by Django 5.2.15 on 2026-07-07 18:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_rls_pricechangerequest'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='pricechangerequest',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='pricechangerequest',
            name='update_update',
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='seen_by_partner',
            field=models.BooleanField(default=False, verbose_name='Visto pelo parceiro'),
        ),
        migrations.AddField(
            model_name='pricechangerequestevent',
            name='seen_by_partner',
            field=models.BooleanField(default=False, verbose_name='Visto pelo parceiro'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id", "seen_by_partner") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id", NEW."seen_by_partner"); RETURN NULL;', hash='afbfcd8d91c84b878b8fe609785802433f4018bb', operation='INSERT', pgid='pgtrigger_insert_insert_4e6cd', table='pricing_pricechangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id", "seen_by_partner") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id", NEW."seen_by_partner"); RETURN NULL;', hash='8597005213e922dd53215ce57dc07c65b38a09a0', operation='UPDATE', pgid='pgtrigger_update_update_3599f', table='pricing_pricechangerequest', when='AFTER')),
        ),
    ]
