# Generated by Django 5.2.15 on 2026-07-16 16:40

import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_buyer_self_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['name'], 'verbose_name': 'Comprador', 'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='lotpricing',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Valoração de lote (congelada)', 'verbose_name_plural': 'Valorações de lote (congeladas)'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['price_list', 'kind', 'gen', 'tier_value'], 'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
        migrations.AlterModelOptions(
            name='pricechangerequest',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['-created_at'], 'verbose_name': 'Mudança de preço (revisão)', 'verbose_name_plural': 'Mudanças de preço (revisão)'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'base_manager_name': 'all_companies', 'default_manager_name': 'all_companies', 'ordering': ['buyer__name', 'brand__name'], 'verbose_name': 'Lista de preços', 'verbose_name_plural': 'Listas de preços'},
        ),
        migrations.AlterModelManagers(
            name='buyer',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lotpricing',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='price',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pricechangerequest',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pricelist',
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='update_update',
        ),
        migrations.AddField(
            model_name='buyer',
            name='fx_usd_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.14'), help_text='US$ por 1 ¥ (ex.: 0.14). Muda só quando o contrato mudar; os preços em ¥ não são afetados.', max_digits=8, verbose_name='Taxa ¥→US$ (contratual)'),
        ),
        migrations.AddField(
            model_name='buyerevent',
            name='fx_usd_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.14'), help_text='US$ por 1 ¥ (ex.: 0.14). Muda só quando o contrato mudar; os preços em ¥ não são afetados.', max_digits=8, verbose_name='Taxa ¥→US$ (contratual)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='3dbd84bb4418394435d22f3ce0a1d676717a5aaa', operation='INSERT', pgid='pgtrigger_insert_insert_35de3', table='pricing_buyer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='023c1492c22a48447646edcf866f820f9e6d9b18', operation='UPDATE', pgid='pgtrigger_update_update_2c806', table='pricing_buyer', when='AFTER')),
        ),
    ]
