# Generated by Django 5.2.15 on 2026-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_buyer_options_alter_lotpricing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço FIXO (2026-07-07): igual ao mínimo.', max_digits=8, null=True, verbose_name='¥ máx. (RMB)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Em yuan (¥). O USD é derivado na leitura: ¥ × taxa contratual do comprador (Buyer.fx_usd_rate).', max_digits=8, null=True, verbose_name='¥ mín. (RMB)'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Novo ¥'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ anterior'),
        ),
        migrations.AlterField(
            model_name='pricechangerequestevent',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Novo ¥'),
        ),
        migrations.AlterField(
            model_name='pricechangerequestevent',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ anterior'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço FIXO (2026-07-07): igual ao mínimo.', max_digits=8, null=True, verbose_name='¥ máx. (RMB)'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Em yuan (¥). O USD é derivado na leitura: ¥ × taxa contratual do comprador (Buyer.fx_usd_rate).', max_digits=8, null=True, verbose_name='¥ mín. (RMB)'),
        ),
    ]
