# Generated by Django 5.2.15 on 2026-07-17 10:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_alter_price_price_max_alter_price_price_min_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='update_update',
        ),
        migrations.AddField(
            model_name='buyer',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='Rótulo NEUTRO exibido a empresas-cliente no lugar do nome (ex.: BUYER-01). Vazio = BUYER-<id>.', max_length=40, verbose_name='Codinome'),
        ),
        migrations.AddField(
            model_name='buyerevent',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='Rótulo NEUTRO exibido a empresas-cliente no lugar do nome (ex.: BUYER-01). Vazio = BUYER-<id>.', max_length=40, verbose_name='Codinome'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_buyerevent" ("active", "codename", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."codename", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='9ad3a4b64604c1b84565fb618dd74027a6fb0f9d', operation='INSERT', pgid='pgtrigger_insert_insert_35de3', table='pricing_buyer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_buyerevent" ("active", "codename", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."codename", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='3f9a50d91b0deab94a941f58ad0d11d6ce81bfd9', operation='UPDATE', pgid='pgtrigger_update_update_2c806', table='pricing_buyer', when='AFTER')),
        ),
    ]
