# Generated by Django 5.2.15 on 2026-07-17 11:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_alter_price_price_max_alter_price_price_min_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='update_update',
        ),
        migrations.AddField(
            model_name='buyer',
            name='prices_in_rmb',
            field=models.BooleanField(default=False, help_text='Trava do migrate_prices_to_rmb: marcado = a migração F10 já rodou neste banco — re-rodar multiplicaria os valores.', verbose_name='Preços já em ¥ (RMB)'),
        ),
        migrations.AddField(
            model_name='buyerevent',
            name='prices_in_rmb',
            field=models.BooleanField(default=False, help_text='Trava do migrate_prices_to_rmb: marcado = a migração F10 já rodou neste banco — re-rodar multiplicaria os valores.', verbose_name='Preços já em ¥ (RMB)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prices_in_rmb", NEW."slug"); RETURN NULL;', hash='771733a3658e03791dbe6ccfd645126a39616443', operation='INSERT', pgid='pgtrigger_insert_insert_35de3', table='pricing_buyer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prices_in_rmb", NEW."slug"); RETURN NULL;', hash='717f788ebc71d9562878e9fbb42231c61ceddd01', operation='UPDATE', pgid='pgtrigger_update_update_2c806', table='pricing_buyer', when='AFTER')),
        ),
    ]
