# Generated by Django 5.2.15 on 2026-07-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_remove_buyer_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8, verbose_name='Tipo')),
                ('gen', models.CharField(blank=True, default='', max_length=12, verbose_name='Geração')),
                ('tier_value', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Faixa')),
                ('tier_unit', models.CharField(max_length=2, verbose_name='Unidade')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Código de categoria (F12)',
                'verbose_name_plural': 'Códigos de categoria (F12)',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'gen', 'tier_value', 'tier_unit'), name='unique_categorycode_key'), models.CheckConstraint(condition=models.Q(('code__gt', 0)), name='categorycode_positive')],
            },
        ),
    ]
