# Generated by Django 5.2.15 on 2026-07-24 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_categorycode'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycode',
            options={'ordering': ['kind', 'code'], 'verbose_name': 'Código de categoria (F12)', 'verbose_name_plural': 'Códigos de categoria (F12)'},
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='price_kind_vocab',
        ),
        migrations.AlterField(
            model_name='categorycode',
            name='code',
            field=models.PositiveIntegerField(verbose_name='Número (na letra)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='gen',
            field=models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4X / DDR3L… Vazio para eMMC/UFS. Em eMCP/uMCP é a geração da RAM.', max_length=12, verbose_name='Geração'),
        ),
        migrations.AlterField(
            model_name='price',
            name='kind',
            field=models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='price',
            name='tier_value',
            field=models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (a RAM fica FORA da chave — regra do comprador). DDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='gen',
            field=models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4X / DDR3L… Vazio para eMMC/UFS. Em eMCP/uMCP é a geração da RAM.', max_length=12, verbose_name='Geração'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='kind',
            field=models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='tier_value',
            field=models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (a RAM fica FORA da chave — regra do comprador). DDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade'),
        ),
        migrations.AddConstraint(
            model_name='categorycode',
            constraint=models.UniqueConstraint(fields=('kind', 'code'), name='unique_categorycode_kind_code'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['ddr', 'emcp', 'emmc', 'lpddr', 'ufs', 'umcp'])), name='price_kind_vocab'),
        ),
    ]
