# Generated by Django 5.2.15 on 2026-07-24 15:37

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_categorycode_por_letra'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='buyer',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='price_kind_vocab',
        ),
        migrations.AddField(
            model_name='buyer',
            name='ssd_rmb_per_gb',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Preço linear do SSD: ¥ por GB (ex.: 0.10 → 512GB = ¥51). Arredonda ao ¥ inteiro. Vazio = SSD sem preço.', max_digits=6, null=True, verbose_name='SSD — ¥ por GB'),
        ),
        migrations.AddField(
            model_name='buyerevent',
            name='ssd_rmb_per_gb',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Preço linear do SSD: ¥ por GB (ex.: 0.10 → 512GB = ¥51). Arredonda ao ¥ inteiro. Vazio = SSD sem preço.', max_digits=6, null=True, verbose_name='SSD — ¥ por GB'),
        ),
        migrations.AlterField(
            model_name='price',
            name='gen',
            field=models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4 / DDR3… Vazio para eMMC/UFS/eMCP/uMCP (v3.1: combo keia SÓ pelo NAND — planilha v9).', max_length=12, verbose_name='Geração'),
        ),
        migrations.AlterField(
            model_name='price',
            name='kind',
            field=models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR'), ('ssd', 'SSD')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='price',
            name='tier_value',
            field=models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (RAM — tamanho E geração — fora da chave; v3.1). DDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='gen',
            field=models.CharField(blank=True, default='', help_text='Token canônico: LPDDR4 / DDR3… Vazio para eMMC/UFS/eMCP/uMCP (v3.1: combo keia SÓ pelo NAND — planilha v9).', max_length=12, verbose_name='Geração'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='kind',
            field=models.CharField(choices=[('emmc', 'eMMC'), ('ufs', 'UFS'), ('emcp', 'eMCP'), ('umcp', 'uMCP'), ('lpddr', 'LPDDR'), ('ddr', 'DDR'), ('ssd', 'SSD')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='priceevent',
            name='tier_value',
            field=models.DecimalField(decimal_places=1, help_text='eMCP/uMCP: GB do NAND (RAM — tamanho E geração — fora da chave; v3.1). DDR: densidade do die em Gb.', max_digits=6, verbose_name='Faixa de capacidade'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prices_in_rmb", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;', hash='d364aa04b784a4a392a747ab554c8759ca950b02', operation='INSERT', pgid='pgtrigger_insert_insert_35de3', table='pricing_buyer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='buyer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prices_in_rmb", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;', hash='13452718511d991421752678f8f8cb0ae90e138d', operation='UPDATE', pgid='pgtrigger_update_update_2c806', table='pricing_buyer', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['ddr', 'emcp', 'emmc', 'lpddr', 'ssd', 'ufs', 'umcp'])), name='price_kind_vocab'),
        ),
    ]
