# Generated by Django 5.2.15 on 2026-07-31 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_buyer_ssd_rate'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='price_fixed_only',
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'quoted'), _negated=True), ('price_min', models.F('price_max')), ('kind__in', ('emcp', 'umcp')), _connector='OR'), name='price_fixed_only'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('price_min__isnull', True), ('price_min__lte', models.F('price_max')), _connector='OR'), name='price_range_ordered'),
        ),
    ]
