# Generated by Django 5.2.15 on 2026-07-31 17:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_faixa_emcp_umcp'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='pricechangerequest',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='pricechangerequest',
            name='update_update',
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='new_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ máx. proposto (faixa)'),
        ),
        migrations.AddField(
            model_name='pricechangerequestevent',
            name='new_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ máx. proposto (faixa)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_price_max", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id", "seen_by_partner") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_price_max", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id", NEW."seen_by_partner"); RETURN NULL;', hash='34badce4c9740f89e7e47e36c82f9593be2f070e', operation='INSERT', pgid='pgtrigger_insert_insert_4e6cd', table='pricing_pricechangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricechangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_pricechangerequestevent" ("company_id", "created_at", "id", "new_price", "new_price_max", "new_status", "old_price", "old_status", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_id", "requested_by_id", "review_status", "reviewed_at", "reviewed_by_id", "seen_by_partner") VALUES (NEW."company_id", NEW."created_at", NEW."id", NEW."new_price", NEW."new_price_max", NEW."new_status", NEW."old_price", NEW."old_status", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_id", NEW."requested_by_id", NEW."review_status", NEW."reviewed_at", NEW."reviewed_by_id", NEW."seen_by_partner"); RETURN NULL;', hash='7921640ddd909778d32b5a1c85032a572edf170b', operation='UPDATE', pgid='pgtrigger_update_update_3599f', table='pricing_pricechangerequest', when='AFTER')),
        ),
    ]
