# Generated by Django 5.2.15 on 2026-08-01 04:54

import pgtrigger.compiler
import pgtrigger.migrations


def _backfill_emmc_origin(apps, schema_editor):
    """2026-08-01: linhas eMMC pré-existentes ganham a origem correta ANTES
    da constraint. Semântica exata do acordo: as linhas da GENÉRICA eram os
    preços unificados (= celular); as linhas de LISTA DE MARCA eram as colunas
    por marca da planilha (= a tabela de PCB do comprador)."""
    # modelo histórico: managers custom não migram — usa o _default_manager
    Price = apps.get_model('pricing', 'Price')
    Price._default_manager.filter(kind='emmc', price_list__brand__isnull=True
                                  ).update(origin='phone')
    Price._default_manager.filter(kind='emmc', price_list__brand__isnull=False
                                  ).update(origin='pcb')


def _reverse_emmc_origin(apps, schema_editor):
    apps.get_model('pricing', 'Price')._default_manager.filter(
        kind='emmc').update(origin='')
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_unified_kinds_faixa_pedido'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='price',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='price',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='unique_price_key',
        ),
        migrations.AddField(
            model_name='price',
            name='origin',
            field=models.CharField(blank=True, choices=[('', '—'), ('phone', 'Celular'), ('pcb', 'PCB')], default='', help_text='SÓ para eMMC (2026-08-01): celular = preço unificado (genérica); PCB = por marca. Demais tipos: vazio.', max_length=5, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='priceevent',
            name='origin',
            field=models.CharField(blank=True, choices=[('', '—'), ('phone', 'Celular'), ('pcb', 'PCB')], default='', help_text='SÓ para eMMC (2026-08-01): celular = preço unificado (genérica); PCB = por marca. Demais tipos: vazio.', max_length=5, verbose_name='Origem'),
        ),
        migrations.RunPython(_backfill_emmc_origin, _reverse_emmc_origin),
        pgtrigger.migrations.AddTrigger(
            model_name='price',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pricing_priceevent" ("company_id", "gen", "id", "kind", "last_updated", "notes", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id", "price_max", "price_min", "quote_date", "source", "status", "tier_unit", "tier_value", "updated_by_id") VALUES (NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."last_updated", NEW."notes", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_list_id", NEW."price_max", NEW."price_min", NEW."quote_date", NEW."source", NEW."status", NEW."tier_unit", NEW."tier_value", NEW."updated_by_id"); RETURN NULL;', hash='300ab47e7b09ea25ded8377202688fbc8d1ddd04', operation='INSERT', pgid='pgtrigger_insert_insert_12aba', table='pricing_price', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='price',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pricing_priceevent" ("company_id", "gen", "id", "kind", "last_updated", "notes", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id", "price_max", "price_min", "quote_date", "source", "status", "tier_unit", "tier_value", "updated_by_id") VALUES (NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."last_updated", NEW."notes", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_list_id", NEW."price_max", NEW."price_min", NEW."quote_date", NEW."source", NEW."status", NEW."tier_unit", NEW."tier_value", NEW."updated_by_id"); RETURN NULL;', hash='54182310dfa733d30f6be8b9fd45e300c181ecb1', operation='UPDATE', pgid='pgtrigger_update_update_c5d0c', table='pricing_price', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('price_list', 'kind', 'gen', 'tier_value', 'tier_unit', 'origin'), name='unique_price_key_origin'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['', 'phone', 'pcb'])), name='price_origin_vocab'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'emmc'), ('origin__in', ['phone', 'pcb'])), models.Q(models.Q(('kind', 'emmc'), _negated=True), ('origin', '')), _connector='OR'), name='price_origin_emmc_only'),
        ),
    ]
