# Generated by Django 5.2.15 on 2026-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_remove_price_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Mid-market do dia (4 casas — PLANO_FX §1.7).', max_digits=8, verbose_name='CNY→USD')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='Fonte')),
                ('is_fallback', models.BooleanField(default=False, help_text='Fonte fora do ar — repetiu a última taxa conhecida.', verbose_name='Fallback')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Buscada em')),
            ],
            options={
                'verbose_name': 'Taxa de câmbio (dia)',
                'verbose_name_plural': 'Taxas de câmbio',
                'ordering': ['-date'],
            },
        ),
    ]
