# Generated by Django 5.2.15 on 2026-08-03 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_comprador_plataforma'),
        ('tenancy', '0004_remove_company_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerevent',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='De quem é este comprador. VAZIO = comprador de PLATAFORMA (dono, 2026-08-03): a tabela dele precifica o lote de TODAS as empresas (comissão sobre o total); a entidade e a gestão continuam só-plataforma (cliente vê "WhatTheChip").', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
    ]
