# K9 — NAND cru TSOP (dono 2026-08-14, HANDOFF_K9): campo Buyer.k9_rmb_each
# (preço FIXO ¥/unidade, padrão ssd_rmb_per_gb — nasce NULL até o OK do Wu
# Quan) + kind 'k9' no vocabulário da chave (constraint price_kind_vocab).
# Espelho pghistory (BuyerEvent) e triggers recriados, como na 0016.
# Generated by Django 5.2.15 on 2026-08-14 14:32

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0022_alter_buyerevent_company"),
        ("tenancy", "0005_alter_company_slug_alter_companyevent_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="buyer",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="buyer",
            name="update_update",
        ),
        migrations.RemoveConstraint(
            model_name="price",
            name="price_kind_vocab",
        ),
        migrations.AddField(
            model_name="buyer",
            name="k9_rmb_each",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço fixo do K9 (NAND cru TSOP): ¥ por unidade (ex.: 1 → 500 un. = ¥500). Vazio = K9 sem preço.",
                max_digits=6,
                null=True,
                verbose_name="K9 — ¥ por unidade",
            ),
        ),
        migrations.AddField(
            model_name="buyerevent",
            name="k9_rmb_each",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço fixo do K9 (NAND cru TSOP): ¥ por unidade (ex.: 1 → 500 un. = ¥500). Vazio = K9 sem preço.",
                max_digits=6,
                null=True,
                verbose_name="K9 — ¥ por unidade",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="kind",
            field=models.CharField(
                choices=[
                    ("emmc", "eMMC"),
                    ("ufs", "UFS"),
                    ("emcp", "eMCP"),
                    ("umcp", "uMCP"),
                    ("lpddr", "LPDDR"),
                    ("ddr", "DDR"),
                    ("ssd", "SSD"),
                    ("k9", "K9"),
                ],
                max_length=8,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="priceevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("emmc", "eMMC"),
                    ("ufs", "UFS"),
                    ("emcp", "eMCP"),
                    ("umcp", "uMCP"),
                    ("lpddr", "LPDDR"),
                    ("ddr", "DDR"),
                    ("ssd", "SSD"),
                    ("k9", "K9"),
                ],
                max_length=8,
                verbose_name="Tipo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="buyer",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "k9_rmb_each", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."k9_rmb_each", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prices_in_rmb", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;',
                    hash="96da95ed60a99eaab494f43f92993ca7034f53a6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_35de3",
                    table="pricing_buyer",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="buyer",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "k9_rmb_each", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."k9_rmb_each", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prices_in_rmb", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;',
                    hash="4bdc2dc7faea2504caeb034c5e37b4e90bf99f57",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_2c806",
                    table="pricing_buyer",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        ["ddr", "emcp", "emmc", "k9", "lpddr", "ssd", "ufs", "umcp"],
                    )
                ),
                name="price_kind_vocab",
            ),
        ),
    ]
