"""Buyer.ship_to_* — destinatário do embarque (dono, 2026-08-18).

ADITIVA, tudo blank/default='' — nenhum backfill (RunPython em tabela com RLS
exige o GUC de plataforma no migrate do Render; ver PRECIFICACAO §12.19). O
endereço entra pelo ADMIN, no comprador ativo. Comprador sem endereço = o PDF
não desenha o bloco SHIP TO.

O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 02:09

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0023_buyer_k9_rate"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="buyer",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="buyer",
            name="update_update",
        ),
        migrations.AddField(
            model_name="buyer",
            name="ship_to_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bloco de endereço como a transportadora deve lê-lo, uma linha por linha (rua, complemento, cidade – código postal). Sem o nome, o e-mail e o telefone: eles têm campo próprio.",
                verbose_name="SHIP TO — endereço",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="ship_to_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="SHIP TO — e-mail"
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="ship_to_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome de quem recebe (não é o nome do comprador).",
                max_length=120,
                verbose_name="SHIP TO — destinatário",
            ),
        ),
        migrations.AddField(
            model_name="buyer",
            name="ship_to_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Com código do país, ex.: (+853) 63525754.",
                max_length=40,
                verbose_name="SHIP TO — telefone",
            ),
        ),
        migrations.AddField(
            model_name="buyerevent",
            name="ship_to_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bloco de endereço como a transportadora deve lê-lo, uma linha por linha (rua, complemento, cidade – código postal). Sem o nome, o e-mail e o telefone: eles têm campo próprio.",
                verbose_name="SHIP TO — endereço",
            ),
        ),
        migrations.AddField(
            model_name="buyerevent",
            name="ship_to_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="SHIP TO — e-mail"
            ),
        ),
        migrations.AddField(
            model_name="buyerevent",
            name="ship_to_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome de quem recebe (não é o nome do comprador).",
                max_length=120,
                verbose_name="SHIP TO — destinatário",
            ),
        ),
        migrations.AddField(
            model_name="buyerevent",
            name="ship_to_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Com código do país, ex.: (+853) 63525754.",
                max_length=40,
                verbose_name="SHIP TO — telefone",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="buyer",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "k9_rmb_each", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "ship_to_address", "ship_to_email", "ship_to_name", "ship_to_phone", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."k9_rmb_each", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prices_in_rmb", NEW."ship_to_address", NEW."ship_to_email", NEW."ship_to_name", NEW."ship_to_phone", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;',
                    hash="bc753ef0f010712c279f8edd4349cde7ccb6d8dc",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_35de3",
                    table="pricing_buyer",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="buyer",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pricing_buyerevent" ("active", "company_id", "created_at", "fx_usd_rate", "id", "k9_rmb_each", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prices_in_rmb", "ship_to_address", "ship_to_email", "ship_to_name", "ship_to_phone", "slug", "ssd_rmb_per_gb") VALUES (NEW."active", NEW."company_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."k9_rmb_each", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prices_in_rmb", NEW."ship_to_address", NEW."ship_to_email", NEW."ship_to_name", NEW."ship_to_phone", NEW."slug", NEW."ssd_rmb_per_gb"); RETURN NULL;',
                    hash="a0b001b5de0e947848d2a8558325912a2073c7f0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_2c806",
                    table="pricing_buyer",
                    when="AFTER",
                ),
            ),
        ),
    ]
