# Generated by Django 6.0.4 on 2026-05-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0005_chipfamily_decode_gen_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipfamily',
            name='decode_cap_map',
            field=models.TextField(blank=True, default='', help_text='Nome do DecodeMap para capacidade. Para eMCP: val_primary=cap NAND, val_secondary=cap RAM'),
        ),
        migrations.AlterField(
            model_name='chipfamily',
            name='decode_cap_pos',
            field=models.IntegerField(blank=True, help_text='Índice (0-based) do 1º char que codifica a capacidade. Ex: KLM[C]G0016A → pos=3', null=True),
        ),
        migrations.AlterField(
            model_name='chipfamily',
            name='decode_density_type',
            field=models.TextField(blank=True, default='', help_text="'pc' ou 'mobile' — ativa decode de densidade DRAM"),
        ),
        migrations.AlterField(
            model_name='chipfamily',
            name='decode_gen_map',
            field=models.TextField(blank=True, default='', help_text="Nome do DecodeMap para geração/tipo RAM. val_primary=geração (ex: 'LPDDR4/4X', 'eMMC 5.1')"),
        ),
        migrations.AlterField(
            model_name='chipfamily',
            name='decode_gen_pos',
            field=models.IntegerField(blank=True, help_text="Índice (0-based) do char que codifica a geração/tipo RAM. Ex: KMR[R]x1000B → pos=2 → 'R'=LPDDR4/4X", null=True),
        ),
    ]
