# Generated by Django 5.2.15 on 2026-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0009_knownpart_fbga_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emcp_min_lpddr_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = LPDDR3 é o mínimo aceito)', verbose_name='eMCP/uMCP — Geração LPDDR mínima')),
                ('emcp_min_ram_gb', models.FloatField(default=1.0, help_text='Chips com menos de X GB de RAM → NÃO RENTÁVEL.', verbose_name='eMCP/uMCP — RAM mínima (GB)')),
                ('emcp_min_nand_gb', models.FloatField(default=8.0, help_text='Chips com menos de X GB de NAND → NÃO RENTÁVEL.', verbose_name='eMCP/uMCP — NAND mínima (GB)')),
                ('emmc_min_cap_gb', models.FloatField(default=4.0, help_text='eMMC com menos de X GB → NÃO RENTÁVEL.  (ex: 4 = a partir de 4 GB)', verbose_name='eMMC — Capacidade mínima (GB)')),
                ('ufs_min_cap_gb', models.FloatField(default=4.0, help_text='UFS com menos de X GB → NÃO RENTÁVEL.', verbose_name='UFS — Capacidade mínima (GB)')),
                ('lpddr_min_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = LPDDR3 é o mínimo)', verbose_name='LPDDR — Geração mínima')),
                ('lpddr3_min_cap_gb', models.FloatField(default=2.0, help_text='Para LPDDR3: abaixo de X GB → NÃO RENTÁVEL.', verbose_name='LPDDR3 — Capacidade mínima (GB)')),
                ('lpddr4plus_min_cap_gb', models.FloatField(default=1.0, help_text='Para LPDDR4 ou superior: abaixo de X GB → NÃO RENTÁVEL.', verbose_name='LPDDR4+ — Capacidade mínima (GB)')),
                ('ddr_min_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = DDR3 é o mínimo)', verbose_name='DDR — Geração mínima')),
                ('ddr3_min_gbit', models.FloatField(default=2.0, help_text='Para DDR3: abaixo de X Gb por die → NÃO RENTÁVEL.  (2 Gb = 256 MB | 4 Gb = 512 MB | 8 Gb = 1 GB)', verbose_name='DDR3 — Densidade mínima (Gb por die)')),
                ('ddr4plus_min_gbit', models.FloatField(default=8.0, help_text='Para DDR4 ou superior: abaixo de X Gb por die → NÃO RENTÁVEL.  (8 Gb = 1 GB | 4 Gb = 512 MB)', verbose_name='DDR4+ — Densidade mínima (Gb por die)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('notes', models.TextField(blank=True, default='', help_text='Registre o motivo das alterações para auditoria futura.', verbose_name='Notas / Histórico de alterações')),
            ],
            options={
                'verbose_name': 'Configuração de Rentabilidade',
                'verbose_name_plural': 'Configuração de Rentabilidade',
            },
        ),
    ]
