# Generated by Django 5.2.15 on 2026-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0010_profitabilityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitabilityconfig',
            name='gddr_min_gen',
            field=models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = GDDR3 é o mínimo; GDDR2 e sem número → NÃO RENTÁVEL)', verbose_name='GDDR — Geração mínima'),
        ),
    ]
