# Generated by Django 5.2.15 on 2026-06-26
#
# Remoção do Gemini e do campo status (jun/2026).
#   - Remove KnownPart.status (raw/enriched/failed): o engine agora trata como
#     autoritativo só confidence ∈ (confirmed, manual). Ver chips/engine.py.
#   - Remove os níveis de IA (ai_high/ai_medium/ai_low) de KnownPart.confidence
#     e o src_type "ai" de Source — não há mais enriquecimento por IA.
#
# Pós-migração (executar pelo usuário, nesta ordem):
#   1. python manage.py migrate                 # aplica este 0012 (dropa a coluna)
#   2. python manage.py purge_enriched --commit # limpa linhas legadas ai_*/estimated/fila raw
#   3. reiniciar o servidor                     # cache do engine (regra de ouro #3)
# A coluna status é DROPADA: o valor antigo de cada linha é descartado (esperado).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0011_profitabilityconfig_gddr_min_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knownpart',
            name='status',
        ),
        migrations.AlterField(
            model_name='knownpart',
            name='confidence',
            field=models.CharField(choices=[('confirmed', '✅ Confirmado'), ('manual', '✏️  Manual'), ('distributor', '🏪 Distribuidor'), ('estimated', '~ Estimado')], default='estimated', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='source_used',
            field=models.TextField(blank=True, default='', help_text='grammar | db_exact | db_fbga | not_found'),
        ),
        migrations.AlterField(
            model_name='source',
            name='src_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraper', 'Scraper'), ('distributor', 'Distribuidor'), ('datasheet', 'Datasheet')], max_length=32),
        ),
    ]
