# Generated by Django 5.2.15 on 2026-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0012_remove_knownpart_status_alter_knownpart_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versão do Catálogo',
                'verbose_name_plural': 'Versão do Catálogo',
            },
        ),
    ]
