# Generated by Django 5.2.15 on 2026-06-30 21:11
# Passo 1A: coluna part_number_norm + backfill (a constraint de unicidade vem na
# migração da PARTE 2, depois do dedupe_known_parts resolver as 22 colisões).

from django.db import migrations, models


def _backfill_norm(apps, schema_editor):
    """Preenche part_number_norm para os registros existentes (em massa)."""
    from chips.normalize import normalize_pn
    KnownPart = apps.get_model("chips", "KnownPart")
    rows = list(KnownPart.objects.all().only("id", "part_number", "part_number_norm"))
    for r in rows:
        r.part_number_norm = normalize_pn(r.part_number)
    KnownPart.objects.bulk_update(rows, ["part_number_norm"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0013_catalogversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownpart',
            name='part_number_norm',
            field=models.TextField(blank=True, db_index=True, default='', help_text='Forma canônica do PN (normalize_pn: NFKC + maiúsc + só A-Z0-9). Preenchida no save(); é a CHAVE de busca do engine (passo 1A).'),
        ),
        migrations.RunPython(_backfill_norm, migrations.RunPython.noop),
    ]
