# Generated by Django 5.2.15 on 2026-06-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0014_knownpart_part_number_norm'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.UniqueConstraint(fields=('part_number_norm',), name='uniq_knownpart_part_number_norm'),
        ),
    ]
