# Generated by Django 5.2.15 on 2026-06-30 22:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0015_knownpart_uniq_knownpart_part_number_norm'),
        ('pages', '0002_remove_ckeditor'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipFamilyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('prefix', models.TextField(help_text='Prefixo do PN, ex: KLM, K4B, H5AN')),
                ('chip_type', models.TextField(help_text='Ex: eMMC, RAM, eMCP, UFS')),
                ('subtype', models.TextField(blank=True, default='', help_text='Ex: DDR3 SDRAM, LPDDR4X')),
                ('interface', models.TextField(blank=True, default='')),
                ('decode_cap_pos', models.IntegerField(blank=True, help_text='Índice (0-based) do 1º char que codifica a capacidade. Ex: KLM[C]G0016A → pos=3', null=True)),
                ('decode_cap_len', models.IntegerField(default=1, help_text="Nº de chars da chave de capacidade (padrão=1). Use 2 para eMCP com pares como 'X1', 'BT', 'GD'")),
                ('decode_cap_map', models.TextField(blank=True, default='', help_text='Nome do DecodeMap para capacidade. Para eMCP: val_primary=cap NAND, val_secondary=cap RAM')),
                ('decode_gen_pos', models.IntegerField(blank=True, help_text="Índice (0-based) do char que codifica a geração/tipo RAM. Ex: KMR[R]x1000B → pos=2 → 'R'=LPDDR4/4X", null=True)),
                ('decode_gen_map', models.TextField(blank=True, default='', help_text="Nome do DecodeMap para geração/tipo RAM. val_primary=geração (ex: 'LPDDR4/4X', 'eMMC 5.1')")),
                ('decode_gen_len', models.IntegerField(default=1, help_text="Nº de chars da chave no mapa de geração/RAM (padrão=1). Use 2 para eMCP com chaves de 2 chars como 'AC', 'AD', 'A8'.")),
                ('decode_density_type', models.TextField(blank=True, default='', help_text="'pc' ou 'mobile' — ativa decode de densidade DRAM")),
                ('pn_length', models.IntegerField(blank=True, help_text='Comprimento canônico do PN (sem sufixo opcional após hífen). Ex: KLM8G1GETF = 10. Usado pela UI de PIN para detectar conclusão da entrada e disparar o decode automaticamente. Deixar em branco se o comprimento for variável.', null=True)),
                ('is_emcp', models.BooleanField(default=False)),
                ('suffix_rules', models.TextField(blank=True, default='', help_text='JSON com regras de sufixo')),
                ('tip', models.TextField(blank=True, default='', help_text='Dica exibida para o operador')),
                ('reasoning', models.TextField(blank=True, default='', help_text='JSON list com passos de raciocínio')),
                ('priority', models.IntegerField(default=100, help_text='Menor = maior prioridade no match de prefixo')),
                ('active', models.BooleanField(default=True)),
                ('is_documented', models.BooleanField(default=True, help_text='False para famílias identificadas mas sem documentação pública verificável. Exibe banner de contribuição na UI e desativa persistência automática na fila.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecodeMapEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('map_name', models.TextField(help_text='Ex: CAP_MAP, DRAM_PC, DRAM_MOBILE, EMMC_GEN')),
                ('char_key', models.TextField(help_text='Chave — caractere ou código do PN')),
                ('val_primary', models.TextField(blank=True, default='', help_text='Valor principal, ex: 16GB')),
                ('val_secondary', models.TextField(blank=True, default='', help_text='Valor secundário, ex: 128MB por die')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnownPartEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('part_number', models.TextField()),
                ('part_number_norm', models.TextField(blank=True, default='', help_text='Forma canônica do PN (normalize_pn: NFKC + maiúsc + só A-Z0-9). Preenchida no save(); é a CHAVE de busca do engine (passo 1A).')),
                ('chip_type', models.TextField(blank=True, default='')),
                ('subtype', models.TextField(blank=True, default='')),
                ('capacity', models.TextField(blank=True, default='', help_text='Ex: 64GB, 512MB')),
                ('density_gbit', models.TextField(blank=True, default='', help_text='Ex: 4Gb (por die)')),
                ('density_gb', models.TextField(blank=True, default='', help_text='Ex: 512MB (por die)')),
                ('emcp_ram', models.TextField(blank=True, default='', help_text='Ex: LPDDR4X 4GB')),
                ('emcp_nand', models.TextField(blank=True, default='', help_text='Ex: eMMC 5.1 64GB')),
                ('interface', models.TextField(blank=True, default='')),
                ('fbga_code', models.CharField(blank=True, default='', help_text='Código FBGA gravado a laser no chip (ex: D9VFC). Micron DRAM mobile: padrão D9XXX. NAND: D8XXX. Permite lookup direto pelo código que o operador lê na esteira, sem precisar digitar o PN completo.', max_length=10)),
                ('device', models.TextField(blank=True, default='', help_text='Ex: Galaxy J3/J5 2016')),
                ('notes', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('confirmed', '✅ Confirmado'), ('manual', '✏️  Manual'), ('distributor', '🏪 Distribuidor'), ('estimated', '~ Estimado')], default='estimated', max_length=20)),
                ('source_url', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityConfigEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('emcp_min_lpddr_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = LPDDR3 é o mínimo aceito)', verbose_name='eMCP/uMCP — Geração LPDDR mínima')),
                ('emcp_min_ram_gb', models.FloatField(default=1.0, help_text='Chips com menos de X GB de RAM → NÃO RENTÁVEL.', verbose_name='eMCP/uMCP — RAM mínima (GB)')),
                ('emcp_min_nand_gb', models.FloatField(default=8.0, help_text='Chips com menos de X GB de NAND → NÃO RENTÁVEL.', verbose_name='eMCP/uMCP — NAND mínima (GB)')),
                ('emmc_min_cap_gb', models.FloatField(default=4.0, help_text='eMMC com menos de X GB → NÃO RENTÁVEL.  (ex: 4 = a partir de 4 GB)', verbose_name='eMMC — Capacidade mínima (GB)')),
                ('ufs_min_cap_gb', models.FloatField(default=4.0, help_text='UFS com menos de X GB → NÃO RENTÁVEL.', verbose_name='UFS — Capacidade mínima (GB)')),
                ('lpddr_min_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = LPDDR3 é o mínimo)', verbose_name='LPDDR — Geração mínima')),
                ('lpddr3_min_cap_gb', models.FloatField(default=2.0, help_text='Para LPDDR3: abaixo de X GB → NÃO RENTÁVEL.', verbose_name='LPDDR3 — Capacidade mínima (GB)')),
                ('lpddr4plus_min_cap_gb', models.FloatField(default=1.0, help_text='Para LPDDR4 ou superior: abaixo de X GB → NÃO RENTÁVEL.', verbose_name='LPDDR4+ — Capacidade mínima (GB)')),
                ('ddr_min_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = DDR3 é o mínimo)', verbose_name='DDR — Geração mínima')),
                ('ddr3_min_gbit', models.FloatField(default=2.0, help_text='Para DDR3: abaixo de X Gb por die → NÃO RENTÁVEL.  (2 Gb = 256 MB | 4 Gb = 512 MB | 8 Gb = 1 GB)', verbose_name='DDR3 — Densidade mínima (Gb por die)')),
                ('ddr4plus_min_gbit', models.FloatField(default=1.0, help_text='Para DDR4 ou superior: abaixo de X Gb por die → NÃO RENTÁVEL.  (1 Gb = 128 MB | 2 Gb = 256 MB | 8 Gb = 1 GB)', verbose_name='DDR4+ — Densidade mínima (Gb por die)')),
                ('gddr_min_gen', models.IntegerField(default=3, help_text='Gerações abaixo deste valor → NÃO RENTÁVEL.  (3 = GDDR3 é o mínimo; GDDR2 e sem número → NÃO RENTÁVEL)', verbose_name='GDDR — Geração mínima')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('notes', models.TextField(blank=True, default='', help_text='Registre o motivo das alterações para auditoria futura.', verbose_name='Notas / Histórico de alterações')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chipfamily',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_chipfamilyevent" ("active", "added_at", "brand_id", "chip_type", "decode_cap_len", "decode_cap_map", "decode_cap_pos", "decode_density_type", "decode_gen_len", "decode_gen_map", "decode_gen_pos", "doc_page_id", "id", "interface", "is_documented", "is_emcp", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pn_length", "prefix", "priority", "reasoning", "subtype", "suffix_rules", "tip") VALUES (NEW."active", NEW."added_at", NEW."brand_id", NEW."chip_type", NEW."decode_cap_len", NEW."decode_cap_map", NEW."decode_cap_pos", NEW."decode_density_type", NEW."decode_gen_len", NEW."decode_gen_map", NEW."decode_gen_pos", NEW."doc_page_id", NEW."id", NEW."interface", NEW."is_documented", NEW."is_emcp", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pn_length", NEW."prefix", NEW."priority", NEW."reasoning", NEW."subtype", NEW."suffix_rules", NEW."tip"); RETURN NULL;', hash='998e5930de87dd814540cf9b619c4d0865addaa2', operation='INSERT', pgid='pgtrigger_insert_insert_da029', table='chips_chipfamily', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chipfamily',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_chipfamilyevent" ("active", "added_at", "brand_id", "chip_type", "decode_cap_len", "decode_cap_map", "decode_cap_pos", "decode_density_type", "decode_gen_len", "decode_gen_map", "decode_gen_pos", "doc_page_id", "id", "interface", "is_documented", "is_emcp", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pn_length", "prefix", "priority", "reasoning", "subtype", "suffix_rules", "tip") VALUES (NEW."active", NEW."added_at", NEW."brand_id", NEW."chip_type", NEW."decode_cap_len", NEW."decode_cap_map", NEW."decode_cap_pos", NEW."decode_density_type", NEW."decode_gen_len", NEW."decode_gen_map", NEW."decode_gen_pos", NEW."doc_page_id", NEW."id", NEW."interface", NEW."is_documented", NEW."is_emcp", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pn_length", NEW."prefix", NEW."priority", NEW."reasoning", NEW."subtype", NEW."suffix_rules", NEW."tip"); RETURN NULL;', hash='dbdd1c78ce4b116c84aef459585dc377f1b9ed8f', operation='UPDATE', pgid='pgtrigger_update_update_f5f7f', table='chips_chipfamily', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='decodemap',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_decodemapevent" ("brand_id", "char_key", "id", "map_name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "val_primary", "val_secondary") VALUES (NEW."brand_id", NEW."char_key", NEW."id", NEW."map_name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."val_primary", NEW."val_secondary"); RETURN NULL;', hash='3236957ea22b0ffe477d3a57a0f5308ead18407a', operation='INSERT', pgid='pgtrigger_insert_insert_d7f70', table='chips_decodemap', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='decodemap',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_decodemapevent" ("brand_id", "char_key", "id", "map_name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "val_primary", "val_secondary") VALUES (NEW."brand_id", NEW."char_key", NEW."id", NEW."map_name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."val_primary", NEW."val_secondary"); RETURN NULL;', hash='0f7bd4859099bf3155e8495b5f5fa2038350114b', operation='UPDATE', pgid='pgtrigger_update_update_27a15', table='chips_decodemap', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_knownpartevent" ("added_at", "brand_id", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "source_url", "subtype") VALUES (NEW."added_at", NEW."brand_id", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_id", NEW."source_url", NEW."subtype"); RETURN NULL;', hash='c902b93a74507c4b9a5bfad3ac775e98724a602e', operation='INSERT', pgid='pgtrigger_insert_insert_1e97e', table='chips_knownpart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_knownpartevent" ("added_at", "brand_id", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "source_url", "subtype") VALUES (NEW."added_at", NEW."brand_id", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_id", NEW."source_url", NEW."subtype"); RETURN NULL;', hash='44aa472a5ef57a940f2360605a484ccc147dc24f', operation='UPDATE', pgid='pgtrigger_update_update_25166', table='chips_knownpart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "gddr_min_gen", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."gddr_min_gen", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='cbfa2552d87e9e57641abdf11359ce639958edd0', operation='INSERT', pgid='pgtrigger_insert_insert_b4a84', table='chips_profitabilityconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "gddr_min_gen", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."gddr_min_gen", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='5efd8c0c6def1b3f8e969ed05b77b31626eaf9fa', operation='UPDATE', pgid='pgtrigger_update_update_6a525', table='chips_profitabilityconfig', when='AFTER')),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='brand',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.brand'),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='doc_page',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Página de documentação correspondente (fab-samsung, fab-hynix...)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='chips.chipfamily'),
        ),
        migrations.AddField(
            model_name='decodemapevent',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Deixar em branco se o mapa for universal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.brand'),
        ),
        migrations.AddField(
            model_name='decodemapevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='decodemapevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='chips.decodemap'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='brand',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.brand'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.chipfamily'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='chips.knownpart'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='chips.source'),
        ),
        migrations.AddField(
            model_name='profitabilityconfigevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='profitabilityconfigevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='chips.profitabilityconfig'),
        ),
    ]
