# Generated by Django 5.2.15 on 2026-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0016_chipfamilyevent_decodemapevent_knownpartevent_and_more'),
        ('pages', '0002_remove_ckeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipfamily',
            name='prefix',
            field=models.TextField(db_index=True, help_text='Prefixo do PN, ex: KLM, K4B, H5AN. Único GLOBAL (constraint em Meta): um prefixo pertence a uma marca só; o engine casa PN→família por prefixo.'),
        ),
        migrations.AlterField(
            model_name='chipfamilyevent',
            name='prefix',
            field=models.TextField(help_text='Prefixo do PN, ex: KLM, K4B, H5AN. Único GLOBAL (constraint em Meta): um prefixo pertence a uma marca só; o engine casa PN→família por prefixo.'),
        ),
        migrations.AddConstraint(
            model_name='chipfamily',
            constraint=models.UniqueConstraint(fields=('prefix',), name='uniq_chipfamily_prefix'),
        ),
    ]
