# Generated by Django 5.2.15 on 2026-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0017_alter_chipfamily_prefix_alter_chipfamilyevent_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogversion',
            name='max_known_parts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
