# Generated by Django 5.2.15 on 2026-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0018_catalogversion_max_known_parts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', ['confirmed', 'manual', 'distributor', 'estimated'])), name='knownpart_confidence_vocab'),
        ),
    ]
