# Generated by Django 5.2.15 on 2026-07-03 14:27

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0019_knownpart_knownpart_confidence_vocab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='knownpart',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='knownpart',
            name='update_update',
        ),
        migrations.AddField(
            model_name='knownpart',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Quem aprovou. Tem que ser ≠ do submitter (four-eyes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_parts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knownpart',
            name='review_status',
            field=models.CharField(choices=[('draft', '📝 Rascunho'), ('submitted', '📤 Submetido (aguardando revisão)'), ('approved', '✅ Aprovado'), ('rejected', '✗ Reprovado'), ('obsolete', '🗑 Obsoleto')], db_index=True, default='approved', help_text="Estado no fluxo de revisão. Só 'approved' é visível/autoritativo no engine.", max_length=20),
        ),
        migrations.AddField(
            model_name='knownpart',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownpart',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Quem submeteu (agente/humano). NULL = pipeline de máquina / seed / legado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_parts_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Quem aprovou. Tem que ser ≠ do submitter (four-eyes).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='review_status',
            field=models.CharField(choices=[('draft', '📝 Rascunho'), ('submitted', '📤 Submetido (aguardando revisão)'), ('approved', '✅ Aprovado'), ('rejected', '✗ Reprovado'), ('obsolete', '🗑 Obsoleto')], default='approved', help_text="Estado no fluxo de revisão. Só 'approved' é visível/autoritativo no engine.", max_length=20),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Quem submeteu (agente/humano). NULL = pipeline de máquina / seed / legado.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_knownpartevent" ("added_at", "approved_by_id", "brand_id", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_status", "reviewed_at", "source_id", "source_url", "submitted_by_id", "subtype") VALUES (NEW."added_at", NEW."approved_by_id", NEW."brand_id", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."review_status", NEW."reviewed_at", NEW."source_id", NEW."source_url", NEW."submitted_by_id", NEW."subtype"); RETURN NULL;', hash='6bbc64b3ae9a1ac059de7a088c000c3316f354b1', operation='INSERT', pgid='pgtrigger_insert_insert_1e97e', table='chips_knownpart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_knownpartevent" ("added_at", "approved_by_id", "brand_id", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_status", "reviewed_at", "source_id", "source_url", "submitted_by_id", "subtype") VALUES (NEW."added_at", NEW."approved_by_id", NEW."brand_id", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."review_status", NEW."reviewed_at", NEW."source_id", NEW."source_url", NEW."submitted_by_id", NEW."subtype"); RETURN NULL;', hash='c14fe4f5eeae0aff94a861ed1e8008ae5e1e5fc0', operation='UPDATE', pgid='pgtrigger_update_update_25166', table='chips_knownpart', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['draft', 'submitted', 'approved', 'rejected', 'obsolete'])), name='knownpart_review_status_vocab'),
        ),
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.CheckConstraint(condition=models.Q(('review_status', 'approved'), ('submitted_by__isnull', False), ('approved_by', models.F('submitted_by')), _negated=True), name='knownpart_four_eyes'),
        ),
    ]
