# Generated by Django 5.2.15 on 2026-07-03 20:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0020_remove_knownpart_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='profitabilityconfig',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='profitabilityconfig',
            name='update_update',
        ),
        migrations.AddField(
            model_name='profitabilityconfig',
            name='gddr_min_gbit',
            field=models.FloatField(default=2.0, help_text='Para GDDR3+: abaixo de X Gb por die → NÃO RENTÁVEL; ≥ X → RENTÁVEL.  (2 Gb = 256 MB | 4 Gb = 512 MB)', verbose_name='GDDR — Densidade mínima (Gb por die)'),
        ),
        migrations.AddField(
            model_name='profitabilityconfigevent',
            name='gddr_min_gbit',
            field=models.FloatField(default=2.0, help_text='Para GDDR3+: abaixo de X Gb por die → NÃO RENTÁVEL; ≥ X → RENTÁVEL.  (2 Gb = 256 MB | 4 Gb = 512 MB)', verbose_name='GDDR — Densidade mínima (Gb por die)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "gddr_min_gbit", "gddr_min_gen", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."gddr_min_gbit", NEW."gddr_min_gen", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='b96e8bb3a6671f94205069e6a9eee722705625d4', operation='INSERT', pgid='pgtrigger_insert_insert_b4a84', table='chips_profitabilityconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "gddr_min_gbit", "gddr_min_gen", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."gddr_min_gbit", NEW."gddr_min_gen", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='2a8ac7fc6206dd4708fca5ffacda5a6961bb14c4', operation='UPDATE', pgid='pgtrigger_update_update_6a525', table='chips_profitabilityconfig', when='AFTER')),
        ),
    ]
