# Generated by Django 5.2.15 on 2026-07-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0021_remove_profitabilityconfig_insert_insert_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='unknownchip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.company', verbose_name='Empresa (1ª a reportar)'),
        ),
    ]
