# Generated by Django 5.2.15 on 2026-07-23 19:44

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0022_searchlog_company_unknownchip_company'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='profitabilityconfig',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='profitabilityconfig',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='profitabilityconfig',
            name='gddr_min_gbit',
        ),
        migrations.RemoveField(
            model_name='profitabilityconfig',
            name='gddr_min_gen',
        ),
        migrations.RemoveField(
            model_name='profitabilityconfigevent',
            name='gddr_min_gbit',
        ),
        migrations.RemoveField(
            model_name='profitabilityconfigevent',
            name='gddr_min_gen',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='436366202b4dda94f2c5268153ec2147079bef1f', operation='INSERT', pgid='pgtrigger_insert_insert_b4a84', table='chips_profitabilityconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='profitabilityconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_profitabilityconfigevent" ("ddr3_min_gbit", "ddr4plus_min_gbit", "ddr_min_gen", "emcp_min_lpddr_gen", "emcp_min_nand_gb", "emcp_min_ram_gb", "emmc_min_cap_gb", "id", "lpddr3_min_cap_gb", "lpddr4plus_min_cap_gb", "lpddr_min_gen", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ufs_min_cap_gb", "updated_at") VALUES (NEW."ddr3_min_gbit", NEW."ddr4plus_min_gbit", NEW."ddr_min_gen", NEW."emcp_min_lpddr_gen", NEW."emcp_min_nand_gb", NEW."emcp_min_ram_gb", NEW."emmc_min_cap_gb", NEW."id", NEW."lpddr3_min_cap_gb", NEW."lpddr4plus_min_cap_gb", NEW."lpddr_min_gen", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."ufs_min_cap_gb", NEW."updated_at"); RETURN NULL;', hash='c6f817818b4e0e02e8a148fd764d8e839c0eab2a', operation='UPDATE', pgid='pgtrigger_update_update_6a525', table='chips_profitabilityconfig', when='AFTER')),
        ),
    ]
