# Generated by Django 5.2.15 on 2026-09-20 01:58

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0023_remove_gddr_thresholds'),
        ('pages', '0004_backfill_pt_br'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='chipfamily',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='chipfamily',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='knownpart',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='knownpart',
            name='update_update',
        ),
        migrations.AddField(
            model_name='chipfamily',
            name='bus_width',
            field=models.TextField(blank=True, default='', help_text='Largura do barramento de DADOS quando é fixa na família (x4/x8/x16/x32/x64) — ou vazio. Família multi-largura (K4B tem x4/x8/x16) deixa VAZIO: quem sabe é o registro, ou a gramática (decode_width_*).'),
        ),
        migrations.AddField(
            model_name='chipfamily',
            name='decode_width_len',
            field=models.IntegerField(default=1, help_text='Nº de chars da chave de largura (padrão=1; Samsung usa 2).'),
        ),
        migrations.AddField(
            model_name='chipfamily',
            name='decode_width_map',
            field=models.TextField(blank=True, default='', help_text="Nome do DecodeMap de largura (val_primary = 'x4'…'x64'). SÓ preencher em família provada pelo coletor."),
        ),
        migrations.AddField(
            model_name='chipfamily',
            name='decode_width_pos',
            field=models.IntegerField(blank=True, help_text='Índice (0-based) do 1º char que codifica a largura. Ex: Samsung K4B2G[08]46D → pos=5. Exige decode_width_map.', null=True),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='bus_width',
            field=models.TextField(blank=True, default='', help_text='Largura do barramento de DADOS quando é fixa na família (x4/x8/x16/x32/x64) — ou vazio. Família multi-largura (K4B tem x4/x8/x16) deixa VAZIO: quem sabe é o registro, ou a gramática (decode_width_*).'),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='decode_width_len',
            field=models.IntegerField(default=1, help_text='Nº de chars da chave de largura (padrão=1; Samsung usa 2).'),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='decode_width_map',
            field=models.TextField(blank=True, default='', help_text="Nome do DecodeMap de largura (val_primary = 'x4'…'x64'). SÓ preencher em família provada pelo coletor."),
        ),
        migrations.AddField(
            model_name='chipfamilyevent',
            name='decode_width_pos',
            field=models.IntegerField(blank=True, help_text='Índice (0-based) do 1º char que codifica a largura. Ex: Samsung K4B2G[08]46D → pos=5. Exige decode_width_map.', null=True),
        ),
        migrations.AddField(
            model_name='knownpart',
            name='bus_width',
            field=models.TextField(blank=True, default='', help_text='Largura do barramento de dados: x4/x8/x16/x32/x64 ou vazio. Vem de datasheet/Tier-1 — NUNCA deduzida do part number (a dedução é do coletor, e deixá-la entrar aqui faria a regra concordar consigo mesma). Vazio obrigatório em eMMC/UFS/eMCP/uMCP.'),
        ),
        migrations.AddField(
            model_name='knownpartevent',
            name='bus_width',
            field=models.TextField(blank=True, default='', help_text='Largura do barramento de dados: x4/x8/x16/x32/x64 ou vazio. Vem de datasheet/Tier-1 — NUNCA deduzida do part number (a dedução é do coletor, e deixá-la entrar aqui faria a regra concordar consigo mesma). Vazio obrigatório em eMMC/UFS/eMCP/uMCP.'),
        ),
        migrations.AlterField(
            model_name='chipfamily',
            name='interface',
            field=models.TextField(blank=True, default='', help_text='VERSÃO DE PROTOCOLO da família (eMMC 5.1, UFS 3.1, Async/ONFI) ou vazio. NUNCA largura de barramento — isso é `bus_width`.'),
        ),
        migrations.AlterField(
            model_name='chipfamilyevent',
            name='interface',
            field=models.TextField(blank=True, default='', help_text='VERSÃO DE PROTOCOLO da família (eMMC 5.1, UFS 3.1, Async/ONFI) ou vazio. NUNCA largura de barramento — isso é `bus_width`.'),
        ),
        migrations.AlterField(
            model_name='knownpart',
            name='interface',
            field=models.TextField(blank=True, default='', help_text='VERSÃO DE PROTOCOLO (eMMC 5.1, UFS 3.1) ou interface física de NAND/NOR (Async/ONFI, SPI). NUNCA largura — isso é `bus_width`.'),
        ),
        migrations.AlterField(
            model_name='knownpartevent',
            name='interface',
            field=models.TextField(blank=True, default='', help_text='VERSÃO DE PROTOCOLO (eMMC 5.1, UFS 3.1) ou interface física de NAND/NOR (Async/ONFI, SPI). NUNCA largura — isso é `bus_width`.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chipfamily',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_chipfamilyevent" ("active", "added_at", "brand_id", "bus_width", "chip_type", "decode_cap_len", "decode_cap_map", "decode_cap_pos", "decode_density_type", "decode_gen_len", "decode_gen_map", "decode_gen_pos", "decode_width_len", "decode_width_map", "decode_width_pos", "doc_page_id", "id", "interface", "is_documented", "is_emcp", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pn_length", "prefix", "priority", "reasoning", "subtype", "suffix_rules", "tip") VALUES (NEW."active", NEW."added_at", NEW."brand_id", NEW."bus_width", NEW."chip_type", NEW."decode_cap_len", NEW."decode_cap_map", NEW."decode_cap_pos", NEW."decode_density_type", NEW."decode_gen_len", NEW."decode_gen_map", NEW."decode_gen_pos", NEW."decode_width_len", NEW."decode_width_map", NEW."decode_width_pos", NEW."doc_page_id", NEW."id", NEW."interface", NEW."is_documented", NEW."is_emcp", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pn_length", NEW."prefix", NEW."priority", NEW."reasoning", NEW."subtype", NEW."suffix_rules", NEW."tip"); RETURN NULL;', hash='9bdd24c77c3f8c02173edead16ed6244d7942951', operation='INSERT', pgid='pgtrigger_insert_insert_da029', table='chips_chipfamily', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chipfamily',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_chipfamilyevent" ("active", "added_at", "brand_id", "bus_width", "chip_type", "decode_cap_len", "decode_cap_map", "decode_cap_pos", "decode_density_type", "decode_gen_len", "decode_gen_map", "decode_gen_pos", "decode_width_len", "decode_width_map", "decode_width_pos", "doc_page_id", "id", "interface", "is_documented", "is_emcp", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pn_length", "prefix", "priority", "reasoning", "subtype", "suffix_rules", "tip") VALUES (NEW."active", NEW."added_at", NEW."brand_id", NEW."bus_width", NEW."chip_type", NEW."decode_cap_len", NEW."decode_cap_map", NEW."decode_cap_pos", NEW."decode_density_type", NEW."decode_gen_len", NEW."decode_gen_map", NEW."decode_gen_pos", NEW."decode_width_len", NEW."decode_width_map", NEW."decode_width_pos", NEW."doc_page_id", NEW."id", NEW."interface", NEW."is_documented", NEW."is_emcp", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pn_length", NEW."prefix", NEW."priority", NEW."reasoning", NEW."subtype", NEW."suffix_rules", NEW."tip"); RETURN NULL;', hash='6294649e4df9f8ec0673ace6e27f04d8f690d489', operation='UPDATE', pgid='pgtrigger_update_update_f5f7f', table='chips_chipfamily', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "chips_knownpartevent" ("added_at", "approved_by_id", "brand_id", "bus_width", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_status", "reviewed_at", "source_id", "source_url", "submitted_by_id", "subtype") VALUES (NEW."added_at", NEW."approved_by_id", NEW."brand_id", NEW."bus_width", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."review_status", NEW."reviewed_at", NEW."source_id", NEW."source_url", NEW."submitted_by_id", NEW."subtype"); RETURN NULL;', hash='9947564b5553ddf649b75847b52fa98ebc1b068c', operation='INSERT', pgid='pgtrigger_insert_insert_1e97e', table='chips_knownpart', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='knownpart',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "chips_knownpartevent" ("added_at", "approved_by_id", "brand_id", "bus_width", "capacity", "chip_type", "confidence", "density_gb", "density_gbit", "device", "emcp_nand", "emcp_ram", "family_id", "fbga_code", "id", "interface", "last_updated", "notes", "part_number", "part_number_norm", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "review_status", "reviewed_at", "source_id", "source_url", "submitted_by_id", "subtype") VALUES (NEW."added_at", NEW."approved_by_id", NEW."brand_id", NEW."bus_width", NEW."capacity", NEW."chip_type", NEW."confidence", NEW."density_gb", NEW."density_gbit", NEW."device", NEW."emcp_nand", NEW."emcp_ram", NEW."family_id", NEW."fbga_code", NEW."id", NEW."interface", NEW."last_updated", NEW."notes", NEW."part_number", NEW."part_number_norm", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."review_status", NEW."reviewed_at", NEW."source_id", NEW."source_url", NEW."submitted_by_id", NEW."subtype"); RETURN NULL;', hash='22fbcbe2cdde783788dfa98ca8e5c4401eef1b14', operation='UPDATE', pgid='pgtrigger_update_update_25166', table='chips_knownpart', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='chipfamily',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width__in', ('', 'x4', 'x8', 'x16', 'x32', 'x64'))), name='chipfamily_bus_width_vocab'),
        ),
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.CheckConstraint(condition=models.Q(('bus_width__in', ('', 'x4', 'x8', 'x16', 'x32', 'x64'))), name='knownpart_bus_width_vocab'),
        ),
    ]
