# Generated by Django 5.2.15 on 2026-09-24 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0024_remove_chipfamily_insert_insert_and_more'),
        ('pages', '0004_backfill_pt_br'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chipfamily',
            constraint=models.CheckConstraint(condition=models.Q(('interface__in', ('x4', 'x8', 'x16', 'x32', 'x64', 'X4', 'X8', 'X16', 'X32', 'X64')), _negated=True), name='chipfamily_interface_nao_e_largura'),
        ),
        migrations.AddConstraint(
            model_name='knownpart',
            constraint=models.CheckConstraint(condition=models.Q(('interface__in', ('x4', 'x8', 'x16', 'x32', 'x64', 'X4', 'X8', 'X16', 'X32', 'X64')), _negated=True), name='knownpart_interface_nao_e_largura'),
        ),
    ]
