# Generated by Django 5.2.13 on 2026-05-04 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador na URL, ex: fab-samsung', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Título completo da página', max_length=300)),
                ('nav_title', models.CharField(blank=True, help_text='Título curto para a sidebar (opcional)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na sidebar')),
                ('section', models.CharField(blank=True, help_text="Seção da sidebar, ex: '2. Fabricantes'", max_length=100)),
                ('content', ckeditor.fields.RichTextField(help_text='Conteúdo HTML da página (edite com CKEditor)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
