# Generated by Django 5.2.15 on 2026-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(blank=True, default='', help_text='Conteúdo HTML da página', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_es',
            field=models.TextField(blank=True, default='', help_text='Conteúdo HTML da página', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_pt_br',
            field=models.TextField(blank=True, default='', help_text='Conteúdo HTML da página', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_zh_hans',
            field=models.TextField(blank=True, default='', help_text='Conteúdo HTML da página', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_title_en',
            field=models.CharField(blank=True, help_text='Título curto para a sidebar (opcional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_title_es',
            field=models.CharField(blank=True, help_text='Título curto para a sidebar (opcional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_title_pt_br',
            field=models.CharField(blank=True, help_text='Título curto para a sidebar (opcional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_title_zh_hans',
            field=models.CharField(blank=True, help_text='Título curto para a sidebar (opcional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='section_en',
            field=models.CharField(blank=True, help_text="Seção da sidebar, ex: '2. Fabricantes'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='section_es',
            field=models.CharField(blank=True, help_text="Seção da sidebar, ex: '2. Fabricantes'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='section_pt_br',
            field=models.CharField(blank=True, help_text="Seção da sidebar, ex: '2. Fabricantes'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='section_zh_hans',
            field=models.CharField(blank=True, help_text="Seção da sidebar, ex: '2. Fabricantes'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(help_text='Título completo da página', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_es',
            field=models.CharField(help_text='Título completo da página', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_pt_br',
            field=models.CharField(help_text='Título completo da página', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_zh_hans',
            field=models.CharField(help_text='Título completo da página', max_length=300, null=True),
        ),
    ]
