# Generated by Django 5.2.15 on 2026-07-06 20:08

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador para rotas/domínio futuros (ex.: "eminer").', max_length=60, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, help_text='Desativar ≠ deletar — o histórico fica.', verbose_name='Ativa')),
                ('last_lot_number', models.PositiveIntegerField(default=0, help_text='Contador atômico da numeração de lote (T2). Não editar à mão.', verbose_name='Último nº de lote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('slug', models.SlugField(db_index=False, help_text='Identificador para rotas/domínio futuros (ex.: "eminer").', max_length=60, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, help_text='Desativar ≠ deletar — o histórico fica.', verbose_name='Ativa')),
                ('last_lot_number', models.PositiveIntegerField(default=0, help_text='Contador atômico da numeração de lote (T2). Não editar à mão.', verbose_name='Último nº de lote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Operador'), ('manager', 'Gerente'), ('admin', 'Admin da empresa')], default='operator', max_length=10, verbose_name='Papel')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Vínculo (papel)',
                'verbose_name_plural': 'Vínculos (papéis)',
                'ordering': ['company__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='MembershipEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('operator', 'Operador'), ('manager', 'Gerente'), ('admin', 'Admin da empresa')], default='operator', max_length=10, verbose_name='Papel')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tenancy.branch')),
                ('company', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='tenancy.company', verbose_name='Empresa'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "last_lot_number", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."last_lot_number", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='17bde2efde6523628adb4dddff8b497618209d1e', operation='INSERT', pgid='pgtrigger_insert_insert_a9a01', table='tenancy_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "last_lot_number", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."last_lot_number", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='a2aec601a91cbfed63107707b023411a5cea8e7e', operation='UPDATE', pgid='pgtrigger_update_update_3e868', table='tenancy_company', when='AFTER')),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='membership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='company',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tenancy.membership'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_branch_company_name'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='branch',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tenancy_branchevent" ("active", "company_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."company_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='3523757863c00f11b38839381c5eddc2621e590e', operation='INSERT', pgid='pgtrigger_insert_insert_0dbf1', table='tenancy_branch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='branch',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tenancy_branchevent" ("active", "company_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."company_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='23d4655ddcf71096724c2b093b26a2f2c53dfea0', operation='UPDATE', pgid='pgtrigger_update_update_5e186', table='tenancy_branch', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['company', 'role'], name='membership_company_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_membership_user_company'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['operator', 'manager', 'admin'])), name='membership_role_vocab'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='membership',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tenancy_membershipevent" ("active", "branch_id", "company_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."active", NEW."branch_id", NEW."company_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='e8f523b86610139eda02609fe3438cf5afe09691', operation='INSERT', pgid='pgtrigger_insert_insert_bd4d0', table='tenancy_membership', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='membership',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tenancy_membershipevent" ("active", "branch_id", "company_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."active", NEW."branch_id", NEW."company_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='c9dce015bfdce164f9bf24cb48809601c2dbae53', operation='UPDATE', pgid='pgtrigger_update_update_c9fda', table='tenancy_membership', when='AFTER')),
        ),
    ]
