# Generated by Django 5.2.15 on 2026-07-06 23:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/JPG. Em produção exige disco persistente (Render) ou S3 — ver nota.', null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/JPG. Em produção exige disco persistente (Render) ou S3 — ver nota.', null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "last_lot_number", "logo", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."last_lot_number", NEW."logo", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='935e27a5ceee19985d7090208144653a8fcc6de5', operation='INSERT', pgid='pgtrigger_insert_insert_a9a01', table='tenancy_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "last_lot_number", "logo", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."last_lot_number", NEW."logo", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='24b165d2b2ac80b262289a40014122e8ebe5fb2a', operation='UPDATE', pgid='pgtrigger_update_update_3e868', table='tenancy_company', when='AFTER')),
        ),
    ]
