# Generated by Django 5.2.15 on 2026-07-08 14:05

import django.db.models.deletion
import tenancy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_remove_company_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=tenancy.models._language_choices, default='', help_text='Vazio = automático (cookie do navegador → idioma do navegador/região).', max_length=10, verbose_name='Idioma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_pref', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de idioma',
                'verbose_name_plural': 'Preferências de idioma',
            },
        ),
    ]
