# Generated by Django 5.2.15 on 2026-07-21 01:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_userlanguage'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        migrations.AddField(
            model_name='company',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='Dona do WhatTheChip: usuários dela veem os rótulos REAIS de categoria. Empresas-cliente veem só o código C-### (F12 — proteção do conhecimento).', verbose_name='Empresa da plataforma'),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='Dona do WhatTheChip: usuários dela veem os rótulos REAIS de categoria. Empresas-cliente veem só o código C-### (F12 — proteção do conhecimento).', verbose_name='Empresa da plataforma'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='09e60ceab8830f5ab3605da2c2fcca42b69e6310', operation='INSERT', pgid='pgtrigger_insert_insert_a9a01', table='tenancy_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='5cccc68564cd5edc2acd3bbe47d87440ca0c3fe9', operation='UPDATE', pgid='pgtrigger_update_update_3e868', table='tenancy_company', when='AFTER')),
        ),
    ]
