# Generated by Django 5.2.15 on 2026-08-07 14:29

import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_remove_company_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                help_text='Identificador de rotas e o SUBDOMÍNIO futuro do cliente (ex.: "eminer" → eminer.whatthechip.app). Quase-permanente: minúsculas, dígitos e hífen (B3).',
                max_length=60,
                unique=True,
                validators=[tenancy.models.validate_company_slug],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="companyevent",
            name="slug",
            field=models.SlugField(
                db_index=False,
                help_text='Identificador de rotas e o SUBDOMÍNIO futuro do cliente (ex.: "eminer" → eminer.whatthechip.app). Quase-permanente: minúsculas, dígitos e hífen (B3).',
                max_length=60,
                validators=[tenancy.models.validate_company_slug],
                verbose_name="Slug",
            ),
        ),
    ]
