# Generated by Django 5.2.15 on 2026-08-16 04:26

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_alter_company_slug_alter_companyevent_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLogo",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="logo_asset",
                        serialize=False,
                        to="tenancy.company",
                        verbose_name="Empresa",
                    ),
                ),
                ("data", models.BinaryField(verbose_name="Bytes do logo")),
            ],
            options={
                "verbose_name": "Logo de empresa",
                "verbose_name_plural": "Logos de empresa",
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.RemoveField(
            model_name="company",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="companyevent",
            name="logo",
        ),
        migrations.AddField(
            model_name="company",
            name="logo_mime",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Vazio = sem logo. Gerido pelo upload no admin — não editar.",
                max_length=32,
                verbose_name="MIME do logo",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Cache-buster (?v=) das tags <img>. Gerido pelo upload.",
                null=True,
                verbose_name="Logo atualizado em",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="logo_mime",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Vazio = sem logo. Gerido pelo upload no admin — não editar.",
                max_length=32,
                verbose_name="MIME do logo",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="logo_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Cache-buster (?v=) das tags <img>. Gerido pelo upload.",
                null=True,
                verbose_name="Logo atualizado em",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;',
                    hash="3c5a51c6e897b434f3237442bdc274d18f1a630d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;',
                    hash="a7cb8ee7442d61f7930a81771d8171ba43a0f1d0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
    ]
