# Generated by Django 5.2.15 on 2026-08-17 12:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0006_company_logo_db"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.AddField(
            model_name="company",
            name="ui_v2",
            field=models.BooleanField(
                default=False,
                help_text="Liga o redesign novo pra ESTA empresa (eMiner primeiro, depois as demais). Tela sem arquivo v2 cai na atual — seguro ligar a qualquer momento; desligar = rollback instantâneo, sem deploy.",
                verbose_name="Frontend v2 (canary)",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="ui_v2",
            field=models.BooleanField(
                default=False,
                help_text="Liga o redesign novo pra ESTA empresa (eMiner primeiro, depois as demais). Tela sem arquivo v2 cai na atual — seguro ligar a qualquer momento; desligar = rollback instantâneo, sem deploy.",
                verbose_name="Frontend v2 (canary)",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="e06fe6f940e80fadb9818fbd58054ae06737cc9e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="0b36053d6d6d2f357cd54e862eed46131171bbf3",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
    ]
