"""Company.address — SHIP FROM do documento de embarque (dono, 2026-08-18).

ADITIVA, blank/default='' — nenhum backfill (o endereço entra pelo admin).
O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 02:41

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_company_ui_v2"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Endereço de embarque desta empresa, uma linha por linha. Aparece no documento que acompanha o lote. Vazio = só o nome da empresa aparece.",
                verbose_name="Endereço (SHIP FROM)",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Endereço de embarque desta empresa, uma linha por linha. Aparece no documento que acompanha o lote. Vazio = só o nome da empresa aparece.",
                verbose_name="Endereço (SHIP FROM)",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="a0132d2de6f5b31070fe4fb93dcce205734e5992",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="9be44e6637c9c8cc1f8513afc723aa49508828ac",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
    ]
