"""Company.code — 2-4 letras que identificam a empresa no documento.

ADITIVA, tudo blank/default='' — **sem backfill de propósito**: documento
existente fica sem `code_str` e a propriedade `code` devolve o formato ANTIGO,
que é o que está no papel já impresso (decisão do dono, 2026-08-18: formato
novo só em documento NOVO).

O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 16:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0008_company_address"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.AddField(
            model_name="company",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nos documentos (ex.: "EMI" → LOT/EMI/041/08/26). Vazio = documentos no formato antigo, sem prefixo.',
                max_length=4,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nos documentos (ex.: "EMI" → LOT/EMI/041/08/26). Vazio = documentos no formato antigo, sem prefixo.',
                max_length=4,
                verbose_name="Código",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="d0a7ebb105bd7a8a9b56b79c238159ff425a6756",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="a939f2eb445c6ce6d2eddc361a50a3d38ab9b20a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="unique_company_code",
            ),
        ),
    ]
