"""Só o help_text do `Company.code`: empresa NOVA agora nasce com código
(as 3 primeiras letras do nome — `suggest_company_code`), então o campo em
branco no admin deixou de significar "documento sem prefixo".

Sem SQL de dado: AlterField de help_text não toca a coluna. O par
company/companyevent é o pghistory espelhando o modelo rastreado.

⚠ O backfill do PASSADO (código nas empresas antigas + `code_str` nos
documentos que já existem) NÃO está aqui: é `manage.py backfill_doc_codes`,
rodado à mão. RunPython em tabela com RLS lê zero linhas sem o GUC de
plataforma, e um backfill que falha dentro do `migrate` aborta o deploy da
Render (o migrate roda no Build Command).
"""

# Generated by Django 5.2.15 on 2026-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0009_company_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nos documentos (ex.: "EMI" → LOT/EMI/041/08/26). Em branco numa empresa NOVA, sai automático: as 3 primeiras letras do nome.',
                max_length=4,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="companyevent",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nos documentos (ex.: "EMI" → LOT/EMI/041/08/26). Em branco numa empresa NOVA, sai automático: as 3 primeiras letras do nome.',
                max_length=4,
                verbose_name="Código",
            ),
        ),
    ]
