# Generated by Django 5.2.15 on 2026-08-19 15:15

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0010_alter_company_code_alter_companyevent_code"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.AddField(
            model_name="company",
            name="service_fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Percentual que o WhatTheChip retém do resultado de cada venda desta empresa. Vale para venda NOVA — o que já foi faturado guarda a taxa da época.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Taxa de serviço (%)",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="service_fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Percentual que o WhatTheChip retém do resultado de cada venda desta empresa. Vale para venda NOVA — o que já foi faturado guarda a taxa da época.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Taxa de serviço (%)",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_fee_pct", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_fee_pct", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="77b48137154c55aadbc1cc3fa08625abb53e90cc",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_fee_pct", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_fee_pct", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="1bbe54d6a35bbc507ac20a5bfaad87c1a1bf118a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
    ]
