# Generated by Django 5.2.15 on 2026-09-01 13:17
#
# Company.payout_on_payment — a chave do repasse automático (dono, 2026-09-01).
#
# ADITIVA e segura no build da Render: só DDL (AddField com default + os
# gatilhos do pghistory recriados porque a tabela de evento ganhou a coluna
# junto). Não há RunPython, então NÃO cai na armadilha do §7 — backfill de
# dados em tabela com RLS roda sem GUC no deploy e casa zero linhas em
# silêncio. Aqui não há dado a mexer: toda empresa existente nasce com a chave
# DESLIGADA, que é o comportamento de hoje.

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0011_company_service_fee"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="company",
            name="update_update",
        ),
        migrations.AddField(
            model_name="company",
            name="payout_on_payment",
            field=models.BooleanField(
                default=False,
                help_text="Ligue APENAS quando o comprador deposita nas contas desta empresa, sem passar pelo WhatTheChip. Aí a quitação da fatura registra sozinha o repasse do líquido. Desligado (padrão), o repasse é lançado à mão quando o WTC transferir.",
                verbose_name="Comprador paga direto ao cliente",
            ),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="payout_on_payment",
            field=models.BooleanField(
                default=False,
                help_text="Ligue APENAS quando o comprador deposita nas contas desta empresa, sem passar pelo WhatTheChip. Aí a quitação da fatura registra sozinha o repasse do líquido. Desligado (padrão), o repasse é lançado à mão quando o WTC transferir.",
                verbose_name="Comprador paga direto ao cliente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "payout_on_payment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_fee_pct", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", NEW."payout_on_payment", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_fee_pct", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="2fb342c0c3b8ea14e07af6b10f1e04ddaf61301e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a9a01",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="company",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tenancy_companyevent" ("active", "address", "code", "created_at", "id", "is_platform", "last_lot_number", "logo_mime", "logo_updated_at", "name", "notes", "payout_on_payment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_fee_pct", "slug", "ui_v2") VALUES (NEW."active", NEW."address", NEW."code", NEW."created_at", NEW."id", NEW."is_platform", NEW."last_lot_number", NEW."logo_mime", NEW."logo_updated_at", NEW."name", NEW."notes", NEW."payout_on_payment", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_fee_pct", NEW."slug", NEW."ui_v2"); RETURN NULL;',
                    hash="ee245b7c55f8116dc44bc11888563646b40e0850",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3e868",
                    table="tenancy_company",
                    when="AFTER",
                ),
            ),
        ),
    ]
