# Generated by Django 5.2.15 on 2026-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_company_payout_on_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, default='', help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nas ordens de venda (ex.: "EMIN" → EMIN-SO-2026-0004). Em branco numa empresa NOVA, sai automático: as 4 primeiras letras do nome. O código do LOTE não leva prefixo.', max_length=4, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='code',
            field=models.CharField(blank=True, default='', help_text='2 a 4 letras MAIÚSCULAS que identificam a empresa nas ordens de venda (ex.: "EMIN" → EMIN-SO-2026-0004). Em branco numa empresa NOVA, sai automático: as 4 primeiras letras do nome. O código do LOTE não leva prefixo.', max_length=4, verbose_name='Código'),
        ),
    ]
