# Generated by Django 5.2.15 on 2026-07-17 01:45

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0015_alter_inventoryentry_options_alter_lot_options_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('pricing', '0012_alter_price_price_max_alter_price_price_min_and_more'),
        ('tenancy', '0003_userlanguage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Cotação (draft)'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='draft', max_length=10, verbose_name='Status')),
                ('fx_usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taxa ¥→US$ (congelada)')),
                ('total_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total ¥')),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total US$')),
                ('unkeyed_units', models.PositiveIntegerField(default=0, verbose_name='Unid. sem chave')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='pricing.buyer', verbose_name='Comprador')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='tenancy.company', verbose_name='Empresa')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='estoque.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Ordem de venda',
                'verbose_name_plural': 'Ordens de venda',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Cotação (draft)'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='draft', max_length=10, verbose_name='Status')),
                ('fx_usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taxa ¥→US$ (congelada)')),
                ('total_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total ¥')),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total US$')),
                ('unkeyed_units', models.PositiveIntegerField(default=0, verbose_name='Unid. sem chave')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pricing.buyer', verbose_name='Comprador')),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('company', models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por')),
                ('lot', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='estoque.lot', verbose_name='Lote')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('kind', models.CharField(max_length=8, verbose_name='Tipo')),
                ('gen', models.CharField(blank=True, default='', max_length=12, verbose_name='Geração')),
                ('tier_value', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Faixa')),
                ('tier_unit', models.CharField(max_length=2, verbose_name='Unidade')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ unitário (congelado)')),
                ('unit_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='US$ unitário (congelado)')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vendas.salesorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Linha da ordem de venda',
                'verbose_name_plural': 'Linhas da ordem de venda',
                'ordering': ['kind', 'brand', 'gen', 'tier_value'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('kind', models.CharField(max_length=8, verbose_name='Tipo')),
                ('gen', models.CharField(blank=True, default='', max_length=12, verbose_name='Geração')),
                ('tier_value', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Faixa')),
                ('tier_unit', models.CharField(max_length=2, verbose_name='Unidade')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='¥ unitário (congelado)')),
                ('unit_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='US$ unitário (congelado)')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.salesorder', verbose_name='Ordem')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.salesorderline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8, verbose_name='Documento')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Último número')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_sequences', to='tenancy.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sequência de documento',
                'verbose_name_plural': 'Sequências de documento',
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
                'constraints': [models.UniqueConstraint(fields=('company', 'kind'), name='unique_docseq_company_kind')],
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_so_company_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('lot',), name='one_active_so_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'confirmed', 'cancelled'])), name='so_status_vocab'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('fx_usd_rate__isnull', False), ('total_rmb__isnull', False), ('total_usd__isnull', False)), _connector='OR'), name='so_confirmed_is_frozen'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorder',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;', hash='ee454707f53d967074b73ec652e8dd9f218f1981', operation='INSERT', pgid='pgtrigger_insert_insert_307b0', table='vendas_salesorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorder',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;', hash='5b466751854d94a59bc942318aa0e5bd2c8cda40', operation='UPDATE', pgid='pgtrigger_update_update_11832', table='vendas_salesorder', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'brand', 'kind', 'gen', 'tier_value', 'tier_unit'), name='unique_so_line_key'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorderline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_salesorderlineevent" ("brand", "company_id", "gen", "id", "kind", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "tier_unit", "tier_value", "unit_rmb", "unit_usd") VALUES (NEW."brand", NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quantity", NEW."tier_unit", NEW."tier_value", NEW."unit_rmb", NEW."unit_usd"); RETURN NULL;', hash='607297bc4121e353870fe20ebacbdbf5cc7b5cbf', operation='INSERT', pgid='pgtrigger_insert_insert_8dc47', table='vendas_salesorderline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorderline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_salesorderlineevent" ("brand", "company_id", "gen", "id", "kind", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "tier_unit", "tier_value", "unit_rmb", "unit_usd") VALUES (NEW."brand", NEW."company_id", NEW."gen", NEW."id", NEW."kind", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quantity", NEW."tier_unit", NEW."tier_value", NEW."unit_rmb", NEW."unit_usd"); RETURN NULL;', hash='8be88cbf8721912c299a0ce08dfb28194d011804', operation='UPDATE', pgid='pgtrigger_update_update_4e4cb', table='vendas_salesorderline', when='AFTER')),
        ),
    ]
