# Generated by Django 5.2.15 on 2026-07-17 12:02

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('tenancy', '0003_userlanguage'),
        ('vendas', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='open', max_length=10, verbose_name='Status')),
                ('fx_usd_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Taxa ¥→US$ (congelada)')),
                ('total_rmb', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total ¥')),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total US$')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitida em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendas.salesorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-issued_at'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor US$')),
                ('paid_at', models.DateField(verbose_name='Data do pagamento')),
                ('reference', models.CharField(blank=True, default='', help_text='Wire/recibo/observação curta.', max_length=120, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendas.invoice', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-paid_at', '-created_at'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor US$')),
                ('paid_at', models.DateField(verbose_name='Data do pagamento')),
                ('reference', models.CharField(blank=True, default='', help_text='Wire/recibo/observação curta.', max_length=120, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('invoice', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.invoice', verbose_name='Fatura')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='vendas.salesorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Acerto (resultado do comprador)',
                'verbose_name_plural': 'Acertos (resultado do comprador)',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='open', max_length=10, verbose_name='Status')),
                ('fx_usd_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Taxa ¥→US$ (congelada)')),
                ('total_rmb', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total ¥')),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total US$')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitida em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.salesorder', verbose_name='Ordem')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.invoice')),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.settlement', verbose_name='Acerto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendas.settlement', verbose_name='Acerto'),
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.salesorder', verbose_name='Ordem')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.settlement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_rejected', models.PositiveIntegerField(default=0, verbose_name='Un. rejeitadas')),
                ('new_unit_rmb', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = mantém o ¥ congelado da OV.', max_digits=8, null=True, verbose_name='Novo ¥ unitário')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='vendas.salesorderline', verbose_name='Linha da ordem')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vendas.settlement', verbose_name='Acerto')),
            ],
            options={
                'verbose_name': 'Linha do acerto',
                'verbose_name_plural': 'Linhas do acerto',
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('qty_rejected', models.PositiveIntegerField(default=0, verbose_name='Un. rejeitadas')),
                ('new_unit_rmb', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = mantém o ¥ congelado da OV.', max_digits=8, null=True, verbose_name='Novo ¥ unitário')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('order_line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.salesorderline', verbose_name='Linha da ordem')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.settlementline')),
                ('settlement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.settlement', verbose_name='Acerto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_usd__gt', 0)), name='payment_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_paymentevent" ("amount_usd", "company_id", "created_at", "created_by_id", "id", "invoice_id", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference") VALUES (NEW."amount_usd", NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."invoice_id", NEW."paid_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference"); RETURN NULL;', hash='1838cba77c0af112687fe9ffe9cd22ae9dbed48d', operation='INSERT', pgid='pgtrigger_insert_insert_1ac83', table='vendas_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_paymentevent" ("amount_usd", "company_id", "created_at", "created_by_id", "id", "invoice_id", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference") VALUES (NEW."amount_usd", NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."invoice_id", NEW."paid_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference"); RETURN NULL;', hash='091904ba9c2455d2367ddb49fb19e4620949b33c', operation='UPDATE', pgid='pgtrigger_update_update_a383a', table='vendas_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='settlement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_settlementevent" ("company_id", "created_at", "created_by_id", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."notes", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='fc76a8930d9fe0c21704e3ad9845f1b458e2a6ac', operation='INSERT', pgid='pgtrigger_insert_insert_93dd5', table='vendas_settlement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='settlement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_settlementevent" ("company_id", "created_at", "created_by_id", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."notes", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='4e6cbe1ef4da5fbe82a4c7845d84c05307ea69a8', operation='UPDATE', pgid='pgtrigger_update_update_0005b', table='vendas_settlement', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_invoice_company_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('order',), name='one_active_invoice_per_order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'paid', 'cancelled'])), name='invoice_status_vocab'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "company_id", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."company_id", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;', hash='6f033fe9745d8752a235aca8161d0b848d81bf8f', operation='INSERT', pgid='pgtrigger_insert_insert_27e04', table='vendas_invoice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "company_id", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."company_id", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;', hash='030989b0f57f41aa02e30992af38aa13b0acb82b', operation='UPDATE', pgid='pgtrigger_update_update_b5653', table='vendas_invoice', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.UniqueConstraint(fields=('settlement', 'order_line'), name='unique_settlement_order_line'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='settlementline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_settlementlineevent" ("company_id", "id", "new_unit_rmb", "order_line_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_rejected", "settlement_id") VALUES (NEW."company_id", NEW."id", NEW."new_unit_rmb", NEW."order_line_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."qty_rejected", NEW."settlement_id"); RETURN NULL;', hash='c64c8baaa1effcd79df6e5276b1595cfab928db8', operation='INSERT', pgid='pgtrigger_insert_insert_aea5f', table='vendas_settlementline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='settlementline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_settlementlineevent" ("company_id", "id", "new_unit_rmb", "order_line_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_rejected", "settlement_id") VALUES (NEW."company_id", NEW."id", NEW."new_unit_rmb", NEW."order_line_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."qty_rejected", NEW."settlement_id"); RETURN NULL;', hash='5c0e0d0e6c784ea184ae79474818f3ce297c5bf5', operation='UPDATE', pgid='pgtrigger_update_update_6df6e', table='vendas_settlementline', when='AFTER')),
        ),
    ]
