"""SalesOrderLine.tier_unit aceita vazio — correção de PROD (2026-08-18).

O K9 (NAND cru TSOP) tem chave PLANA: preço fixo por unidade, sem capacidade,
gravado como tier_value=1 / tier_unit=''. Sem `blank=True` o full_clean() do
portão do modelo recusava a linha, o `except` do create_draft_for_lot engolia a
exceção (fechamento de lote NUNCA trava por causa da venda) e o lote fechava em
silêncio, SEM Ordem de Venda. Live desde o push do K9 em 2026-08-16.

Só metadado de validação — NÃO altera coluna nem dado (o CharField já aceitava
''  no banco). Segura em prod, sem janela.
"""

# Generated by Django 5.2.15 on 2026-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_rls_f114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderline",
            name="tier_unit",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="Unidade"
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineevent",
            name="tier_unit",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="Unidade"
            ),
        ),
    ]
