"""SalesOrder.code_str e Invoice.code_str — códigos CONGELADOS na criação.

ADITIVA, tudo blank/default='' — **sem backfill de propósito**: documento
existente fica sem `code_str` e a propriedade `code` devolve o formato ANTIGO,
que é o que está no papel já impresso (decisão do dono, 2026-08-18: formato
novo só em documento NOVO).

O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 16:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_salesorderline_tier_unit_blank"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="invoice",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="invoice",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="update_update",
        ),
        migrations.AddField(
            model_name="invoice",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="code_str",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Código",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="invoice",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "code_str", "company_id", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."code_str", NEW."company_id", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;',
                    hash="bef7624c96b808278c44e58bc6526d2cae67eb63",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_27e04",
                    table="vendas_invoice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="invoice",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "code_str", "company_id", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."code_str", NEW."company_id", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;',
                    hash="93f64c55525d3d8483628cdbda37c09661beea7a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_b5653",
                    table="vendas_invoice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;',
                    hash="e47ddc732c550b5af52c285f2f7262cccb174547",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_307b0",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;',
                    hash="51749e14b6a6fcd21f5dbea1671082a8b45fb825",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_11832",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
    ]
