"""SalesOrder.received_at — a caixa chegou (dono, 2026-08-18).

Primeiro pedaço do despacho (F4) a existir: é o que o card de etapas da tela
do comprador precisa para dizer em que pé está a compra. Quem marca é o
COMPRADOR — é ele que recebe.

ADITIVA e NULLABLE, **sem backfill de propósito**: compra anterior a isto não
tem a data, e o card mostra a etapa sem carimbo. Backfill em tabela com RLS
precisaria do GUC de plataforma dentro do migrate do Render (armadilha §6.2.2),
e não há data nenhuma a recuperar.

O ciclo remove/recria trigger é do pghistory (coluna nova em modelo rastreado).
"""

# Generated by Django 5.2.15 on 2026-08-18 18:52

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0006_doc_code_str"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="update_update",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o comprador confirmou que a caixa chegou.",
                null=True,
                verbose_name="Recebida em",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o comprador confirmou que a caixa chegou.",
                null=True,
                verbose_name="Recebida em",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;',
                    hash="50aa0c754ba4158e0aa5b1cfbfad3dcdf7eb1db7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_307b0",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "status", "total_rmb", "total_usd", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."unkeyed_units"); RETURN NULL;',
                    hash="06b972618cabaf5e4a58109139b027b4b8f00685",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_11832",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
    ]
