"""PaymentReceipt — o comprovante do pagamento, em BYTES no banco.

⚠ No banco e não em disco (mesma razão do logo da empresa, E4/B7): o
filesystem da Render é EFÊMERO e /media/ nem é servido com DEBUG=False.
Comprovante de pagamento é a última coisa do sistema que pode evaporar num
deploy.

Tabela nova e VAZIA — nada a backfillar. O RLS dela vem na 0009, separada de
propósito: criar tabela e ligar policy são coisas diferentes, e a 0009 é
Postgres-only (no-op no SQLite dos testes).
"""

# Generated by Django 5.2.15 on 2026-08-18 20:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0010_alter_company_code_alter_companyevent_code"),
        ("vendas", "0007_remove_salesorder_insert_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="receipt",
                        serialize=False,
                        to="vendas.payment",
                        verbose_name="Pagamento",
                    ),
                ),
                ("data", models.BinaryField(verbose_name="Bytes do comprovante")),
                ("mime", models.CharField(max_length=32, verbose_name="MIME")),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="Nome do arquivo",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Anexado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante",
                "verbose_name_plural": "Comprovantes",
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
            },
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
    ]
