"""O DESPACHO (F4): transportadora, rastreio e data de envio na SalesOrder.

UMA caixa por lote (decisão do dono, 2026-08-18) — por isso campos aqui, e não
um modelo de volume. Quem preenche é o CLIENTE (gerente ou admin da empresa),
que é quem embala e leva na transportadora.

ADITIVA e toda nullable/blank, **sem backfill**: ordem anterior a isto não tem
despacho registrado, e o card de etapas mostra "Enviado" sem carimbo em vez de
inventar data. Não há dado a recuperar — a informação nunca existiu no sistema.

O ciclo remove/recria trigger é do pghistory (colunas novas em modelo
rastreado). ⚠ Rastreio e transportadora entram no event store de propósito:
corrigir um rastreio é evento de negócio, e a correção tem que ficar auditável.
"""

# Generated by Django 5.2.15 on 2026-08-18 22:19

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0009_paymentreceipt_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="salesorder",
            name="update_update",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="carrier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DHL, FedEx, UPS… como aparece na etiqueta.",
                max_length=40,
                verbose_name="Transportadora",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipped_at",
            field=models.DateField(
                blank=True,
                help_text="O dia em que a caixa saiu.",
                null=True,
                verbose_name="Despachada em",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Despachada por",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tracking",
            field=models.CharField(
                blank=True,
                default="",
                help_text="O número que o comprador acompanha. Pode ser preenchido depois do envio.",
                max_length=60,
                verbose_name="Rastreio",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="carrier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DHL, FedEx, UPS… como aparece na etiqueta.",
                max_length=40,
                verbose_name="Transportadora",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="shipped_at",
            field=models.DateField(
                blank=True,
                help_text="O dia em que a caixa saiu.",
                null=True,
                verbose_name="Despachada em",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Despachada por",
            ),
        ),
        migrations.AddField(
            model_name="salesorderevent",
            name="tracking",
            field=models.CharField(
                blank=True,
                default="",
                help_text="O número que o comprador acompanha. Pode ser preenchido depois do envio.",
                max_length=60,
                verbose_name="Rastreio",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "carrier", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "shipped_at", "shipped_by_id", "status", "total_rmb", "total_usd", "tracking", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."carrier", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."shipped_at", NEW."shipped_by_id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."tracking", NEW."unkeyed_units"); RETURN NULL;',
                    hash="dd8ec5569d5f04408e0879349911ef7566637622",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_307b0",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="salesorder",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "carrier", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "shipped_at", "shipped_by_id", "status", "total_rmb", "total_usd", "tracking", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."carrier", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."shipped_at", NEW."shipped_by_id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."tracking", NEW."unkeyed_units"); RETURN NULL;',
                    hash="c0d82dcccf6fe2f26f9ded0ba8eb1cface85fcfc",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_11832",
                    table="vendas_salesorder",
                    when="AFTER",
                ),
            ),
        ),
    ]
