# Generated by Django 5.2.15 on 2026-08-19 15:21

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0011_company_service_fee"),
        ("vendas", "0010_remove_salesorder_insert_insert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor US$"
                    ),
                ),
                ("paid_at", models.DateField(verbose_name="Data do repasse")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wire/recibo/observação curta.",
                        max_length=120,
                        verbose_name="Referência",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Repasse ao cliente",
                "verbose_name_plural": "Repasses ao cliente",
                "ordering": ["-paid_at", "-created_at"],
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
            },
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="invoice",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="invoice",
            name="update_update",
        ),
        migrations.AddField(
            model_name="invoice",
            name="fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Taxa de serviço (%)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fee_rmb",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Taxa ¥",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Taxa US$",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="fee_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Taxa de serviço (%)",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="fee_rmb",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Taxa ¥",
            ),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Taxa US$",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="invoice",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "code_str", "company_id", "fee_pct", "fee_rmb", "fee_usd", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."code_str", NEW."company_id", NEW."fee_pct", NEW."fee_rmb", NEW."fee_usd", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;',
                    hash="fa1ca67853990ea30ff08a813512ff17dead0436",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_27e04",
                    table="vendas_invoice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="invoice",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vendas_invoiceevent" ("cancelled_at", "code_str", "company_id", "fee_pct", "fee_rmb", "fee_usd", "fx_usd_rate", "id", "issued_at", "issued_by_id", "number", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settlement_id", "status", "total_rmb", "total_usd") VALUES (NEW."cancelled_at", NEW."code_str", NEW."company_id", NEW."fee_pct", NEW."fee_rmb", NEW."fee_usd", NEW."fx_usd_rate", NEW."id", NEW."issued_at", NEW."issued_by_id", NEW."number", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."settlement_id", NEW."status", NEW."total_rmb", NEW."total_usd"); RETURN NULL;',
                    hash="b72ccd1451298efd08f1514247887d4788c5532f",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_b5653",
                    table="vendas_invoice",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="company",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="vendas.invoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_usd__gt", 0)), name="payout_positive"
            ),
        ),
    ]
