"""Pagamento com chave de IDEMPOTÊNCIA (spec v2 do comprador §5.4, 2026-08-26).

"O comprador está em rede instável e vai clicar duas vezes. Um pagamento
duplicado é dinheiro perdido." Das quatro mutações da ficha, três já se
defendiam: `mark_received` é idempotente por construção (a primeira data vale)
e `settle_and_invoice` recusa OV que já tem fatura ativa. O PAGAMENTO não tinha
nada — e um PARCIAL duplicado passa nas duas validações de saldo, porque depois
do primeiro ainda sobra saldo para o segundo.

A chave nasce no render do formulário (uma por página servida). Dois cliques no
mesmo botão mandam a mesma chave; recarregar a página é intenção nova e gera
outra.

A UniqueConstraint é PARCIAL (exclui a string vazia) de propósito: pagamento
registrado sem chave — admin, shell, e todas as linhas que já existem — não
pode passar a colidir com o próximo. Sem o `condition`, o 2º pagamento manual
de qualquer fatura seria recusado.

Campo NULLABLE-equivalente (blank + default='') e sem backfill: a migração roda
em prod sem janela, e o código antigo continua funcionando enquanto o deploy
não chega (ver a regra de nunca migrar prod à frente do deploy).

O churn de triggers é do pghistory: adicionar coluna a modelo rastreado
regenera insert_insert/update_update. Gerado pelo Django, não escrito à mão.
"""

# Generated by Django 5.2.15 on 2026-08-26 15:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_company_service_fee'),
        ('vendas', '0013_backfill_invoice_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='update_update',
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Chave de idempotência'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Chave de idempotência'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_paymentevent" ("amount_usd", "company_id", "created_at", "created_by_id", "id", "idempotency_key", "invoice_id", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference") VALUES (NEW."amount_usd", NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."idempotency_key", NEW."invoice_id", NEW."paid_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference"); RETURN NULL;', hash='133a75539acc698347576d84b37b4aeb6dee3c2a', operation='INSERT', pgid='pgtrigger_insert_insert_1ac83', table='vendas_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_paymentevent" ("amount_usd", "company_id", "created_at", "created_by_id", "id", "idempotency_key", "invoice_id", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference") VALUES (NEW."amount_usd", NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."idempotency_key", NEW."invoice_id", NEW."paid_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference"); RETURN NULL;', hash='6bce4be85aedeb51f945e61a11a7e8b30191b0e3', operation='UPDATE', pgid='pgtrigger_update_update_a383a', table='vendas_payment', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('invoice', 'idempotency_key'), name='payment_idempotency_per_invoice'),
        ),
    ]
