"""Observação da conferência com AUTOR e DATA (spec v2 do comprador §6.9).

Até aqui existia UMA nota por compra, escondida no `Settlement.notes`: sem
autor visível, sem data visível, escrita uma vez no diálogo de fechar
resultado e nunca mais. Se o comprador lembrasse de algo depois — a caixa
chegou molhada, faltou fita, o rastreio estava errado — não havia onde pôr.

O `Settlement.notes` NÃO é removido: continua como registro interno do acerto
(auditoria de quem fechou o quê, com qual observação, naquele instante). O que
muda é quem a TELA e o PDF leem — passa a ser esta tabela. A 0017 traz as
notas que já existem para cá, uma por acerto.

`created_by` é SET_NULL: desativar a conta de um parceiro não pode apagar o
histórico da compra. `order` é PROTECT como todo o resto de vendas.
"""

# Generated by Django 5.2.15 on 2026-08-26 18:08

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('tenancy', '0011_company_service_fee'),
        ('vendas', '0014_payment_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_notes', to='vendas.salesorder', verbose_name='Ordem de venda')),
            ],
            options={
                'verbose_name': 'Observação da conferência',
                'verbose_name_plural': 'Observações da conferência',
                'ordering': ['created_at', 'pk'],
                'base_manager_name': 'all_companies',
                'default_manager_name': 'all_companies',
            },
            managers=[
                ('all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderNoteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('text', models.TextField(verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='tenancy.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='vendas.salesorder', verbose_name='Ordem de venda')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='vendas.ordernote')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordernote',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_ordernoteevent" ("company_id", "created_at", "created_by_id", "id", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "text") VALUES (NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."text"); RETURN NULL;', hash='7712e0235add039e05e8d7d92755945d0eccd0f8', operation='INSERT', pgid='pgtrigger_insert_insert_a7855', table='vendas_ordernote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordernote',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_ordernoteevent" ("company_id", "created_at", "created_by_id", "id", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "text") VALUES (NEW."company_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."text"); RETURN NULL;', hash='1519db9a900fe4a3a4549298a41420e8b3be8151', operation='UPDATE', pgid='pgtrigger_update_update_6349f', table='vendas_ordernote', when='AFTER')),
        ),
    ]
