"""A carteira que RECEBE o pagamento do comprador (spec v2 do comprador §3.12).

É a carteira do WhatTheChip, nunca a do vendedor: todo pagamento de toda compra
vai para este endereço. Mandar o comprador pagar o vendedor direto pularia a
plataforma e quebraria as duas pernas do dinheiro de uma vez.

⚠ SEM `company` e SEM RLS, de propósito, pela mesma razão do `FxRate`: não há
dado por-empresa aqui. É UM endereço, da plataforma, que todo comprador lê. Uma
coluna de empresa criaria a pergunta "a carteira de quem?", que não existe.

Nasce VAZIA — nenhuma linha é semeada. Inventar um endereço padrão seria pôr
dinheiro de verdade a caminho de um lugar imaginário. Enquanto não houver
carteira cadastrada, a tela DIZ que não há, e o botão de pagar fica fora do ar.
"""

# Generated by Django 5.2.15 on 2026-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_backfill_ordernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='WhatTheChip Ltd.', max_length=120, verbose_name='Titular')),
                ('net', models.CharField(default='USDT · TRC-20', help_text='Ex.: USDT · TRC-20. Aparece ao lado do endereço, porque rede errada perde a transferência.', max_length=60, verbose_name='Rede')),
                ('addr', models.CharField(max_length=120, verbose_name='Endereço')),
                ('memo', models.TextField(blank=True, default='', help_text='O que o comprador deve pôr no campo memo/referência da transferência — normalmente o código da ordem (SO).', verbose_name='Instrução de memo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Carteira de recebimento',
                'verbose_name_plural': 'Carteiras de recebimento',
                'ordering': ['-updated_at'],
            },
        ),
    ]
