# Generated by Django 5.2.15 on 2026-09-01 16:02
#
# Wallet ganha `company` (dono, 2026-09-01): "deve existir ambas
# possibilidades, do comprador pagar direto ao cliente e também direto a WTC".
#
# ADITIVA e sem backfill DE PROPÓSITO: toda linha existente fica com
# `company = NULL`, isto é, vira a carteira da PLATAFORMA — que é o que a
# tabela declarava ser. Se a linha que está lá guarda na verdade o endereço
# de um CLIENTE, quem sabe disso é o dono, e o conserto é um campo no admin.
# Adivinhar aqui seria escolher para onde vai dinheiro de verdade a partir de
# um palpite; sem o palpite, o pior caso é a tela dizer "carteira não
# cadastrada" — lento e certo, em vez de rápido e errado.
#
# A política de RLS vem na 0020, separada como o resto de `vendas`.

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0012_company_payout_on_payment"),
        ("vendas", "0018_wallet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
                "ordering": ["-updated_at"],
                "verbose_name": "Carteira de recebimento",
                "verbose_name_plural": "Carteiras de recebimento",
            },
        ),
        migrations.AlterModelManagers(
            name="wallet",
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="wallet",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="VAZIO = carteira do WhatTheChip (o comprador paga a plataforma). PREENCHIDO = carteira deste cliente, para quando o comprador paga direto a ele.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallets",
                to="tenancy.company",
                verbose_name="Empresa",
            ),
        ),
    ]
