# Generated by Django 5.2.15 on 2026-09-02 15:23

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_remove_lot_insert_insert_remove_lot_update_update_and_more'),
        ('pricing', '0028_ratechangerequest_rls'),
        ('tenancy', '0013_alter_company_code_alter_companyevent_code'),
        ('vendas', '0020_wallet_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='salesorder',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='salesorder',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='docsequence',
            name='unique_docseq_company_kind',
        ),
        migrations.RemoveConstraint(
            model_name='salesorder',
            name='unique_so_company_number',
        ),
        migrations.AddField(
            model_name='docsequence',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_year',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ano do documento'),
        ),
        migrations.AddField(
            model_name='salesorderevent',
            name='doc_year',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ano do documento'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorder',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "carrier", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "doc_year", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "shipped_at", "shipped_by_id", "status", "total_rmb", "total_usd", "tracking", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."carrier", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."doc_year", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."shipped_at", NEW."shipped_by_id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."tracking", NEW."unkeyed_units"); RETURN NULL;', hash='93fa563f70b25f39fcf3774e734a9226d912dde4', operation='INSERT', pgid='pgtrigger_insert_insert_307b0', table='vendas_salesorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='salesorder',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "vendas_salesorderevent" ("buyer_id", "cancelled_at", "cancelled_by_id", "carrier", "code_str", "company_id", "confirmed_at", "confirmed_by_id", "created_at", "doc_year", "fx_usd_rate", "id", "lot_id", "notes", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "shipped_at", "shipped_by_id", "status", "total_rmb", "total_usd", "tracking", "unkeyed_units") VALUES (NEW."buyer_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."carrier", NEW."code_str", NEW."company_id", NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."doc_year", NEW."fx_usd_rate", NEW."id", NEW."lot_id", NEW."notes", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."shipped_at", NEW."shipped_by_id", NEW."status", NEW."total_rmb", NEW."total_usd", NEW."tracking", NEW."unkeyed_units"); RETURN NULL;', hash='8b655e9057a1f881a6980895e0dea559fe9aa85b', operation='UPDATE', pgid='pgtrigger_update_update_11832', table='vendas_salesorder', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='docsequence',
            constraint=models.UniqueConstraint(fields=('company', 'kind', 'year'), name='unique_docseq_company_kind_year'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'doc_year', 'number'), name='unique_so_company_year_number'),
        ),
    ]
