# Generated by Django 5.2.15 on 2026-09-07 17:38

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0013_alter_company_code_alter_companyevent_code"),
        ("vendas", "0022_backfill_doc_year_e_sequencias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejections",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Recusas digitadas"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observação digitada"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Salvo em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_draft",
                        to="vendas.salesorder",
                        verbose_name="Ordem de venda",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Salvo por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rascunho da conferência",
                "verbose_name_plural": "Rascunhos da conferência",
                "ordering": ["-updated_at"],
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
            },
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
    ]
