# Generated by Django 5.2.15 on 2026-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0024_settlementdraft_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementdraft",
            name="prices",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preços repactuados (rascunho)"
            ),
        ),
    ]
