# Generated by Django 5.2.15 on 2026-09-10 13:38

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0013_alter_company_code_alter_companyevent_code"),
        ("vendas", "0025_settlementdraft_prices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefeitoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(max_length=40, unique=True, verbose_name="Código"),
                ),
                (
                    "nome_pt",
                    models.CharField(max_length=60, verbose_name="Nome (português)"),
                ),
                (
                    "nome_es",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Nome (espanhol)",
                    ),
                ),
                (
                    "nome_zh",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Nome (chinês)",
                    ),
                ),
                (
                    "nome_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Nome (inglês)",
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("recusa", "Recusa — o chip não serve"),
                            ("desconto", "Desconto — serve, vale menos"),
                        ],
                        default="desconto",
                        max_length=10,
                        verbose_name="Severidade",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Ordem na tela"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tipo de defeito",
                "verbose_name_plural": "Tipos de defeito",
                "ordering": ["ordem", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Prova",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrada em"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "defeitos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="provas",
                        to="vendas.defeitotipo",
                        verbose_name="Defeitos",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provas",
                        to="vendas.salesorderline",
                        verbose_name="Linha",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provas",
                        to="vendas.salesorder",
                        verbose_name="Ordem de venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prova da conferência",
                "verbose_name_plural": "Provas da conferência",
                "ordering": ["created_at", "pk"],
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
            },
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProvaFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField(verbose_name="Bytes da foto (1600px)")),
                ("thumb", models.BinaryField(verbose_name="Bytes da miniatura")),
                (
                    "mime",
                    models.CharField(
                        default="image/jpeg", max_length=32, verbose_name="MIME"
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="Nome original",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Largura"),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Altura"),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Anexada em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "prova",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="vendas.prova",
                        verbose_name="Prova",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto da prova",
                "verbose_name_plural": "Fotos da prova",
                "ordering": ["ordem", "pk"],
                "base_manager_name": "all_companies",
                "default_manager_name": "all_companies",
            },
            managers=[
                ("all_companies", django.db.models.manager.Manager()),
            ],
        ),
    ]
